// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: brtuitongziSZHS.proto

package _go

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// kindID 2005
// 上庄喝水版
//36个筒子加4个白板 白板算半点
//白板 = 10
// 1~9筒 = 1~9
//场景
type BrTuitongziSZHSSceneResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp   int64           `protobuf:"varint,1,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`      //时间戳
	Inning      string          `protobuf:"bytes,2,opt,name=Inning,proto3" json:"Inning,omitempty"`             //牌局号
	Chips       []int32         `protobuf:"varint,3,rep,packed,name=Chips,proto3" json:"Chips,omitempty"`       //筹 码
	AwardAreas  [][]byte        `protobuf:"bytes,4,rep,name=AwardAreas,proto3" json:"AwardAreas,omitempty"`     //开奖记录(路单)
	AreaBets    []int64         `protobuf:"varint,5,rep,packed,name=AreaBets,proto3" json:"AreaBets,omitempty"` //各下注区当前总下注额
	MyBets      []int64         `protobuf:"varint,6,rep,packed,name=MyBets,proto3" json:"MyBets,omitempty"`     //个人在各下注区的总下注额
	AllPlayers  *PlayerListInfo `protobuf:"bytes,7,opt,name=AllPlayers,proto3" json:"AllPlayers,omitempty"`     //玩家列表
	RemainCount int32           `protobuf:"varint,8,opt,name=RemainCount,proto3" json:"RemainCount,omitempty"`  //剩余张数
	StartArea   int32           `protobuf:"varint,9,opt,name=StartArea,proto3" json:"StartArea,omitempty"`
}

func (x *BrTuitongziSZHSSceneResp) Reset() {
	*x = BrTuitongziSZHSSceneResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSSceneResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSSceneResp) ProtoMessage() {}

func (x *BrTuitongziSZHSSceneResp) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSSceneResp.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSSceneResp) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{0}
}

func (x *BrTuitongziSZHSSceneResp) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *BrTuitongziSZHSSceneResp) GetInning() string {
	if x != nil {
		return x.Inning
	}
	return ""
}

func (x *BrTuitongziSZHSSceneResp) GetChips() []int32 {
	if x != nil {
		return x.Chips
	}
	return nil
}

func (x *BrTuitongziSZHSSceneResp) GetAwardAreas() [][]byte {
	if x != nil {
		return x.AwardAreas
	}
	return nil
}

func (x *BrTuitongziSZHSSceneResp) GetAreaBets() []int64 {
	if x != nil {
		return x.AreaBets
	}
	return nil
}

func (x *BrTuitongziSZHSSceneResp) GetMyBets() []int64 {
	if x != nil {
		return x.MyBets
	}
	return nil
}

func (x *BrTuitongziSZHSSceneResp) GetAllPlayers() *PlayerListInfo {
	if x != nil {
		return x.AllPlayers
	}
	return nil
}

func (x *BrTuitongziSZHSSceneResp) GetRemainCount() int32 {
	if x != nil {
		return x.RemainCount
	}
	return 0
}

func (x *BrTuitongziSZHSSceneResp) GetStartArea() int32 {
	if x != nil {
		return x.StartArea
	}
	return 0
}

//状态
// 服务端推送
//(开始 - 定庄)
type BrTuitongziSZHSStateStartResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times     *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
	StartArea int32     `protobuf:"varint,2,opt,name=StartArea,proto3" json:"StartArea,omitempty"` // 开始发牌区域
	Dice      []byte    `protobuf:"bytes,3,opt,name=Dice,proto3" json:"Dice,omitempty"`            // 两个骰子点数(决定起始发牌区域)
	Inning    string    `protobuf:"bytes,4,opt,name=Inning,proto3" json:"Inning,omitempty"`        // 牌局号
}

func (x *BrTuitongziSZHSStateStartResp) Reset() {
	*x = BrTuitongziSZHSStateStartResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSStateStartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSStateStartResp) ProtoMessage() {}

func (x *BrTuitongziSZHSStateStartResp) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSStateStartResp.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSStateStartResp) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{1}
}

func (x *BrTuitongziSZHSStateStartResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *BrTuitongziSZHSStateStartResp) GetStartArea() int32 {
	if x != nil {
		return x.StartArea
	}
	return 0
}

func (x *BrTuitongziSZHSStateStartResp) GetDice() []byte {
	if x != nil {
		return x.Dice
	}
	return nil
}

func (x *BrTuitongziSZHSStateStartResp) GetInning() string {
	if x != nil {
		return x.Inning
	}
	return ""
}

//(下注)
type BrTuitongziSZHSStatePlayingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
}

func (x *BrTuitongziSZHSStatePlayingResp) Reset() {
	*x = BrTuitongziSZHSStatePlayingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSStatePlayingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSStatePlayingResp) ProtoMessage() {}

func (x *BrTuitongziSZHSStatePlayingResp) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSStatePlayingResp.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSStatePlayingResp) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{2}
}

func (x *BrTuitongziSZHSStatePlayingResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

//(开奖)
type BrTuitongziSZHSStateOpenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times    *TimeInfo                `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
	OpenInfo *BrTuitongziSZHSOpenResp `protobuf:"bytes,2,opt,name=OpenInfo,proto3" json:"OpenInfo,omitempty"`
}

func (x *BrTuitongziSZHSStateOpenResp) Reset() {
	*x = BrTuitongziSZHSStateOpenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSStateOpenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSStateOpenResp) ProtoMessage() {}

func (x *BrTuitongziSZHSStateOpenResp) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSStateOpenResp.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSStateOpenResp) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{3}
}

func (x *BrTuitongziSZHSStateOpenResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *BrTuitongziSZHSStateOpenResp) GetOpenInfo() *BrTuitongziSZHSOpenResp {
	if x != nil {
		return x.OpenInfo
	}
	return nil
}

//(结束)
type BrTuitongziSZHSStateOverResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
}

func (x *BrTuitongziSZHSStateOverResp) Reset() {
	*x = BrTuitongziSZHSStateOverResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSStateOverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSStateOverResp) ProtoMessage() {}

func (x *BrTuitongziSZHSStateOverResp) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSStateOverResp.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSStateOverResp) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{4}
}

func (x *BrTuitongziSZHSStateOverResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

//游戏消息
//下注
type BrTuitongziSZHSBetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BetArea  int32 `protobuf:"varint,1,opt,name=BetArea,proto3" json:"BetArea,omitempty"`   // 下注区域
	BetScore int64 `protobuf:"varint,2,opt,name=BetScore,proto3" json:"BetScore,omitempty"` // 下注金额
}

func (x *BrTuitongziSZHSBetReq) Reset() {
	*x = BrTuitongziSZHSBetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSBetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSBetReq) ProtoMessage() {}

func (x *BrTuitongziSZHSBetReq) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSBetReq.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSBetReq) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{5}
}

func (x *BrTuitongziSZHSBetReq) GetBetArea() int32 {
	if x != nil {
		return x.BetArea
	}
	return 0
}

func (x *BrTuitongziSZHSBetReq) GetBetScore() int64 {
	if x != nil {
		return x.BetScore
	}
	return 0
}

type BrTuitongziSZHSBetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   uint64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BetArea  int32  `protobuf:"varint,2,opt,name=BetArea,proto3" json:"BetArea,omitempty"`   // 下注区域
	BetScore int64  `protobuf:"varint,3,opt,name=BetScore,proto3" json:"BetScore,omitempty"` // 下注金额
	OrderId  int32  `protobuf:"varint,4,opt,name=OrderId,proto3" json:"OrderId,omitempty"`   // 结算序号
}

func (x *BrTuitongziSZHSBetResp) Reset() {
	*x = BrTuitongziSZHSBetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSBetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSBetResp) ProtoMessage() {}

func (x *BrTuitongziSZHSBetResp) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSBetResp.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSBetResp) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{6}
}

func (x *BrTuitongziSZHSBetResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *BrTuitongziSZHSBetResp) GetBetArea() int32 {
	if x != nil {
		return x.BetArea
	}
	return 0
}

func (x *BrTuitongziSZHSBetResp) GetBetScore() int64 {
	if x != nil {
		return x.BetScore
	}
	return 0
}

func (x *BrTuitongziSZHSBetResp) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

//开奖
type BrTuitongziSZHSOpenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AwardArea  []byte    `protobuf:"bytes,1,opt,name=AwardArea,proto3" json:"AwardArea,omitempty"`   // 各区域胜负：1胜，0负, 2平
	BankerCard *CardInfo `protobuf:"bytes,2,opt,name=BankerCard,proto3" json:"BankerCard,omitempty"` // 庄
	ShunCard   *CardInfo `protobuf:"bytes,3,opt,name=ShunCard,proto3" json:"ShunCard,omitempty"`     // 顺
	TianCard   *CardInfo `protobuf:"bytes,4,opt,name=TianCard,proto3" json:"TianCard,omitempty"`     // 天
	DiCard     *CardInfo `protobuf:"bytes,5,opt,name=DiCard,proto3" json:"DiCard,omitempty"`         // 地
}

func (x *BrTuitongziSZHSOpenResp) Reset() {
	*x = BrTuitongziSZHSOpenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSOpenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSOpenResp) ProtoMessage() {}

func (x *BrTuitongziSZHSOpenResp) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSOpenResp.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSOpenResp) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{7}
}

func (x *BrTuitongziSZHSOpenResp) GetAwardArea() []byte {
	if x != nil {
		return x.AwardArea
	}
	return nil
}

func (x *BrTuitongziSZHSOpenResp) GetBankerCard() *CardInfo {
	if x != nil {
		return x.BankerCard
	}
	return nil
}

func (x *BrTuitongziSZHSOpenResp) GetShunCard() *CardInfo {
	if x != nil {
		return x.ShunCard
	}
	return nil
}

func (x *BrTuitongziSZHSOpenResp) GetTianCard() *CardInfo {
	if x != nil {
		return x.TianCard
	}
	return nil
}

func (x *BrTuitongziSZHSOpenResp) GetDiCard() *CardInfo {
	if x != nil {
		return x.DiCard
	}
	return nil
}

//结算
type BrTuitongziSZHSCheckoutResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyAcquire int64   `protobuf:"varint,1,opt,name=MyAcquire,proto3" json:"MyAcquire,omitempty"`      // 获得金币(结算)
	Acquires  []int64 `protobuf:"varint,2,rep,packed,name=Acquires,proto3" json:"Acquires,omitempty"` // 各个区域输赢情况
	OrderId   int32   `protobuf:"varint,3,opt,name=OrderId,proto3" json:"OrderId,omitempty"`          // 结算排序
	DrinkGold int64   `protobuf:"varint,4,opt,name=DrinkGold,proto3" json:"DrinkGold,omitempty"`      // 喝水金额
}

func (x *BrTuitongziSZHSCheckoutResp) Reset() {
	*x = BrTuitongziSZHSCheckoutResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSCheckoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSCheckoutResp) ProtoMessage() {}

func (x *BrTuitongziSZHSCheckoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSCheckoutResp.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSCheckoutResp) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{8}
}

func (x *BrTuitongziSZHSCheckoutResp) GetMyAcquire() int64 {
	if x != nil {
		return x.MyAcquire
	}
	return 0
}

func (x *BrTuitongziSZHSCheckoutResp) GetAcquires() []int64 {
	if x != nil {
		return x.Acquires
	}
	return nil
}

func (x *BrTuitongziSZHSCheckoutResp) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *BrTuitongziSZHSCheckoutResp) GetDrinkGold() int64 {
	if x != nil {
		return x.DrinkGold
	}
	return 0
}

//抢庄
type BrTuitongziSZHSHostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsWant    bool  `protobuf:"varint,1,opt,name=IsWant,proto3" json:"IsWant,omitempty"`       // true上庄 false取消上庄
	BankScore int64 `protobuf:"varint,2,opt,name=BankScore,proto3" json:"BankScore,omitempty"` // 上庄/下庄金额(单位:分)
}

func (x *BrTuitongziSZHSHostReq) Reset() {
	*x = BrTuitongziSZHSHostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSHostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSHostReq) ProtoMessage() {}

func (x *BrTuitongziSZHSHostReq) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSHostReq.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSHostReq) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{9}
}

func (x *BrTuitongziSZHSHostReq) GetIsWant() bool {
	if x != nil {
		return x.IsWant
	}
	return false
}

func (x *BrTuitongziSZHSHostReq) GetBankScore() int64 {
	if x != nil {
		return x.BankScore
	}
	return 0
}

type BrTuitongziSZHSHostResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID    uint64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	IsWant    bool   `protobuf:"varint,2,opt,name=IsWant,proto3" json:"IsWant,omitempty"`       // true上庄 false取消上庄
	BankScore int64  `protobuf:"varint,3,opt,name=BankScore,proto3" json:"BankScore,omitempty"` // 上庄/下庄金额(单位:分)
}

func (x *BrTuitongziSZHSHostResp) Reset() {
	*x = BrTuitongziSZHSHostResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSHostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSHostResp) ProtoMessage() {}

func (x *BrTuitongziSZHSHostResp) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSHostResp.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSHostResp) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{10}
}

func (x *BrTuitongziSZHSHostResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *BrTuitongziSZHSHostResp) GetIsWant() bool {
	if x != nil {
		return x.IsWant
	}
	return false
}

func (x *BrTuitongziSZHSHostResp) GetBankScore() int64 {
	if x != nil {
		return x.BankScore
	}
	return 0
}

//// 下庄 (游戏开始不能下庄)
type BrTuitongziSZHSLeaveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BrTuitongziSZHSLeaveReq) Reset() {
	*x = BrTuitongziSZHSLeaveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSLeaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSLeaveReq) ProtoMessage() {}

func (x *BrTuitongziSZHSLeaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSLeaveReq.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSLeaveReq) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{11}
}

type BrTuitongziSZHSLeaveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       uint64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	PreBankScore int64  `protobuf:"varint,2,opt,name=PreBankScore,proto3" json:"PreBankScore,omitempty"` // 上庄前的金额(单位:分)
	WinScore     int64  `protobuf:"varint,3,opt,name=WinScore,proto3" json:"WinScore,omitempty"`         // 输赢金额(单位:分)
	NowScore     int64  `protobuf:"varint,4,opt,name=NowScore,proto3" json:"NowScore,omitempty"`         // 当前金额(单位:分)
}

func (x *BrTuitongziSZHSLeaveResp) Reset() {
	*x = BrTuitongziSZHSLeaveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSLeaveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSLeaveResp) ProtoMessage() {}

func (x *BrTuitongziSZHSLeaveResp) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSLeaveResp.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSLeaveResp) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{12}
}

func (x *BrTuitongziSZHSLeaveResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *BrTuitongziSZHSLeaveResp) GetPreBankScore() int64 {
	if x != nil {
		return x.PreBankScore
	}
	return 0
}

func (x *BrTuitongziSZHSLeaveResp) GetWinScore() int64 {
	if x != nil {
		return x.WinScore
	}
	return 0
}

func (x *BrTuitongziSZHSLeaveResp) GetNowScore() int64 {
	if x != nil {
		return x.NowScore
	}
	return 0
}

////////////////////////////////////////
//主动拉取结果
type BrTuitongziSZHSOpenCardsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"` //
}

func (x *BrTuitongziSZHSOpenCardsReq) Reset() {
	*x = BrTuitongziSZHSOpenCardsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSOpenCardsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSOpenCardsReq) ProtoMessage() {}

func (x *BrTuitongziSZHSOpenCardsReq) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSOpenCardsReq.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSOpenCardsReq) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{13}
}

func (x *BrTuitongziSZHSOpenCardsReq) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type BrTuitongziSZHSOpenCardsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   uint64                   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	OpenInfo *BrTuitongziSZHSOpenResp `protobuf:"bytes,2,opt,name=OpenInfo,proto3" json:"OpenInfo,omitempty"` // 开奖信息
}

func (x *BrTuitongziSZHSOpenCardsResp) Reset() {
	*x = BrTuitongziSZHSOpenCardsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSOpenCardsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSOpenCardsResp) ProtoMessage() {}

func (x *BrTuitongziSZHSOpenCardsResp) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSOpenCardsResp.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSOpenCardsResp) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{14}
}

func (x *BrTuitongziSZHSOpenCardsResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *BrTuitongziSZHSOpenCardsResp) GetOpenInfo() *BrTuitongziSZHSOpenResp {
	if x != nil {
		return x.OpenInfo
	}
	return nil
}

//控制协议
type BrTuitongziSZHSControlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID     uint64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BankerCard *CardInfo `protobuf:"bytes,2,opt,name=BankerCard,proto3" json:"BankerCard,omitempty"` // 庄
	ShunCard   *CardInfo `protobuf:"bytes,3,opt,name=ShunCard,proto3" json:"ShunCard,omitempty"`     // 顺
	TianCard   *CardInfo `protobuf:"bytes,4,opt,name=TianCard,proto3" json:"TianCard,omitempty"`     // 天
	DiCard     *CardInfo `protobuf:"bytes,5,opt,name=DiCard,proto3" json:"DiCard,omitempty"`         // 地
}

func (x *BrTuitongziSZHSControlReq) Reset() {
	*x = BrTuitongziSZHSControlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSControlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSControlReq) ProtoMessage() {}

func (x *BrTuitongziSZHSControlReq) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSControlReq.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSControlReq) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{15}
}

func (x *BrTuitongziSZHSControlReq) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *BrTuitongziSZHSControlReq) GetBankerCard() *CardInfo {
	if x != nil {
		return x.BankerCard
	}
	return nil
}

func (x *BrTuitongziSZHSControlReq) GetShunCard() *CardInfo {
	if x != nil {
		return x.ShunCard
	}
	return nil
}

func (x *BrTuitongziSZHSControlReq) GetTianCard() *CardInfo {
	if x != nil {
		return x.TianCard
	}
	return nil
}

func (x *BrTuitongziSZHSControlReq) GetDiCard() *CardInfo {
	if x != nil {
		return x.DiCard
	}
	return nil
}

type BrTuitongziSZHSControlResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   uint64                   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	OpenInfo *BrTuitongziSZHSOpenResp `protobuf:"bytes,2,opt,name=OpenInfo,proto3" json:"OpenInfo,omitempty"` // 开奖信息
}

func (x *BrTuitongziSZHSControlResp) Reset() {
	*x = BrTuitongziSZHSControlResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSControlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSControlResp) ProtoMessage() {}

func (x *BrTuitongziSZHSControlResp) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSControlResp.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSControlResp) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{16}
}

func (x *BrTuitongziSZHSControlResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *BrTuitongziSZHSControlResp) GetOpenInfo() *BrTuitongziSZHSOpenResp {
	if x != nil {
		return x.OpenInfo
	}
	return nil
}

/////////////预留协议///////////////////////////
//超级抢庄 = 当前庄家的两倍
type BrTuitongziSZHSSuperHostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsWant bool `protobuf:"varint,1,opt,name=IsWant,proto3" json:"IsWant,omitempty"` // true上庄 false取消
}

func (x *BrTuitongziSZHSSuperHostReq) Reset() {
	*x = BrTuitongziSZHSSuperHostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSSuperHostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSSuperHostReq) ProtoMessage() {}

func (x *BrTuitongziSZHSSuperHostReq) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSSuperHostReq.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSSuperHostReq) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{17}
}

func (x *BrTuitongziSZHSSuperHostReq) GetIsWant() bool {
	if x != nil {
		return x.IsWant
	}
	return false
}

type BrTuitongziSZHSSuperHostResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	IsWant bool   `protobuf:"varint,2,opt,name=IsWant,proto3" json:"IsWant,omitempty"` // true上庄 false取消
}

func (x *BrTuitongziSZHSSuperHostResp) Reset() {
	*x = BrTuitongziSZHSSuperHostResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brtuitongziSZHS_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrTuitongziSZHSSuperHostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrTuitongziSZHSSuperHostResp) ProtoMessage() {}

func (x *BrTuitongziSZHSSuperHostResp) ProtoReflect() protoreflect.Message {
	mi := &file_brtuitongziSZHS_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrTuitongziSZHSSuperHostResp.ProtoReflect.Descriptor instead.
func (*BrTuitongziSZHSSuperHostResp) Descriptor() ([]byte, []int) {
	return file_brtuitongziSZHS_proto_rawDescGZIP(), []int{18}
}

func (x *BrTuitongziSZHSSuperHostResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *BrTuitongziSZHSSuperHostResp) GetIsWant() bool {
	if x != nil {
		return x.IsWant
	}
	return false
}

var File_brtuitongziSZHS_proto protoreflect.FileDescriptor

var file_brtuitongziSZHS_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x72, 0x74, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x5a, 0x48,
	0x53, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x67, 0x6f, 0x1a, 0x0e, 0x67, 0x61, 0x6d,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae, 0x02, 0x0a, 0x18,
	0x42, 0x72, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53, 0x53,
	0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x6e, 0x6e, 0x69, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x14,
	0x0a, 0x05, 0x43, 0x68, 0x69, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x43,
	0x68, 0x69, 0x70, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x77, 0x61, 0x72, 0x64, 0x41, 0x72, 0x65,
	0x61, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x41, 0x77, 0x61, 0x72, 0x64, 0x41,
	0x72, 0x65, 0x61, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x72, 0x65, 0x61, 0x42, 0x65, 0x74, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x41, 0x72, 0x65, 0x61, 0x42, 0x65, 0x74, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x4d, 0x79, 0x42, 0x65, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x06, 0x4d, 0x79, 0x42, 0x65, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67,
	0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0a, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x0b,
	0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x72, 0x65, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x72, 0x65, 0x61, 0x22, 0x8d, 0x01, 0x0a,
	0x1d, 0x42, 0x72, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22,
	0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x72, 0x65, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x72, 0x65, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x44, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x45, 0x0a, 0x1f,
	0x42, 0x72, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x22, 0x7b, 0x0a, 0x1c, 0x42, 0x72, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67,
	0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x2e, 0x42,
	0x72, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53, 0x4f, 0x70,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x42, 0x0a, 0x1c, 0x42, 0x72, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53,
	0x5a, 0x48, 0x53, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x22, 0x4d, 0x0a, 0x15, 0x42, 0x72, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e,
	0x67, 0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x42, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x42, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x65, 0x74, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x65, 0x74, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x22, 0x80, 0x01, 0x0a, 0x16, 0x42, 0x72, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e,
	0x67, 0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53, 0x42, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x65, 0x74, 0x41, 0x72, 0x65,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x42, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61,
	0x12, 0x1a, 0x0a, 0x08, 0x42, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x42, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0xdf, 0x01, 0x0a, 0x17, 0x42, 0x72, 0x54, 0x75, 0x69,
	0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x77, 0x61, 0x72, 0x64, 0x41, 0x72, 0x65, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x41, 0x77, 0x61, 0x72, 0x64, 0x41, 0x72, 0x65, 0x61,
	0x12, 0x2c, 0x0a, 0x0a, 0x42, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0a, 0x42, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x12, 0x28,
	0x0a, 0x08, 0x53, 0x68, 0x75, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x53, 0x68, 0x75, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x12, 0x28, 0x0a, 0x08, 0x54, 0x69, 0x61, 0x6e,
	0x43, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e,
	0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x54, 0x69, 0x61, 0x6e, 0x43, 0x61,
	0x72, 0x64, 0x12, 0x24, 0x0a, 0x06, 0x44, 0x69, 0x43, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x06, 0x44, 0x69, 0x43, 0x61, 0x72, 0x64, 0x22, 0x8f, 0x01, 0x0a, 0x1b, 0x42, 0x72, 0x54,
	0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x79, 0x41, 0x63,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x4d, 0x79, 0x41,
	0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x44, 0x72, 0x69, 0x6e, 0x6b, 0x47, 0x6f, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x47, 0x6f, 0x6c, 0x64, 0x22, 0x4e, 0x0a, 0x16, 0x42, 0x72,
	0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x57, 0x61, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x49, 0x73, 0x57, 0x61, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x42, 0x61, 0x6e, 0x6b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x42, 0x61, 0x6e, 0x6b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x67, 0x0a, 0x17, 0x42, 0x72,
	0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x49, 0x73, 0x57, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x49,
	0x73, 0x57, 0x61, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x61, 0x6e, 0x6b, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x42, 0x61, 0x6e, 0x6b, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x42, 0x72, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67,
	0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x22, 0x8e,
	0x01, 0x0a, 0x18, 0x42, 0x72, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x5a,
	0x48, 0x53, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x42, 0x61, 0x6e, 0x6b, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x50, 0x72, 0x65, 0x42, 0x61,
	0x6e, 0x6b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x57, 0x69, 0x6e, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x57, 0x69, 0x6e, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f, 0x77, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4e, 0x6f, 0x77, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22,
	0x35, 0x0a, 0x1b, 0x42, 0x72, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x5a,
	0x48, 0x53, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x6f, 0x0a, 0x1c, 0x42, 0x72, 0x54, 0x75, 0x69, 0x74,
	0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x61, 0x72,
	0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x37,
	0x0a, 0x08, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x2e, 0x42, 0x72, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a,
	0x69, 0x53, 0x5a, 0x48, 0x53, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x4f,
	0x70, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xdb, 0x01, 0x0a, 0x19, 0x42, 0x72, 0x54, 0x75,
	0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x2c, 0x0a,
	0x0a, 0x42, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0a, 0x42, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x12, 0x28, 0x0a, 0x08, 0x53,
	0x68, 0x75, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x53, 0x68, 0x75,
	0x6e, 0x43, 0x61, 0x72, 0x64, 0x12, 0x28, 0x0a, 0x08, 0x54, 0x69, 0x61, 0x6e, 0x43, 0x61, 0x72,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x54, 0x69, 0x61, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x12,
	0x24, 0x0a, 0x06, 0x44, 0x69, 0x43, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x44,
	0x69, 0x43, 0x61, 0x72, 0x64, 0x22, 0x6d, 0x0a, 0x1a, 0x42, 0x72, 0x54, 0x75, 0x69, 0x74, 0x6f,
	0x6e, 0x67, 0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x37, 0x0a, 0x08, 0x4f,
	0x70, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x67, 0x6f, 0x2e, 0x42, 0x72, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x5a,
	0x48, 0x53, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x4f, 0x70, 0x65, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x35, 0x0a, 0x1b, 0x42, 0x72, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e,
	0x67, 0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53, 0x53, 0x75, 0x70, 0x65, 0x72, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x57, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x49, 0x73, 0x57, 0x61, 0x6e, 0x74, 0x22, 0x4e, 0x0a, 0x1c, 0x42,
	0x72, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x5a, 0x48, 0x53, 0x53, 0x75,
	0x70, 0x65, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x57, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x49, 0x73, 0x57, 0x61, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_brtuitongziSZHS_proto_rawDescOnce sync.Once
	file_brtuitongziSZHS_proto_rawDescData = file_brtuitongziSZHS_proto_rawDesc
)

func file_brtuitongziSZHS_proto_rawDescGZIP() []byte {
	file_brtuitongziSZHS_proto_rawDescOnce.Do(func() {
		file_brtuitongziSZHS_proto_rawDescData = protoimpl.X.CompressGZIP(file_brtuitongziSZHS_proto_rawDescData)
	})
	return file_brtuitongziSZHS_proto_rawDescData
}

var file_brtuitongziSZHS_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_brtuitongziSZHS_proto_goTypes = []interface{}{
	(*BrTuitongziSZHSSceneResp)(nil),        // 0: go.BrTuitongziSZHSSceneResp
	(*BrTuitongziSZHSStateStartResp)(nil),   // 1: go.BrTuitongziSZHSStateStartResp
	(*BrTuitongziSZHSStatePlayingResp)(nil), // 2: go.BrTuitongziSZHSStatePlayingResp
	(*BrTuitongziSZHSStateOpenResp)(nil),    // 3: go.BrTuitongziSZHSStateOpenResp
	(*BrTuitongziSZHSStateOverResp)(nil),    // 4: go.BrTuitongziSZHSStateOverResp
	(*BrTuitongziSZHSBetReq)(nil),           // 5: go.BrTuitongziSZHSBetReq
	(*BrTuitongziSZHSBetResp)(nil),          // 6: go.BrTuitongziSZHSBetResp
	(*BrTuitongziSZHSOpenResp)(nil),         // 7: go.BrTuitongziSZHSOpenResp
	(*BrTuitongziSZHSCheckoutResp)(nil),     // 8: go.BrTuitongziSZHSCheckoutResp
	(*BrTuitongziSZHSHostReq)(nil),          // 9: go.BrTuitongziSZHSHostReq
	(*BrTuitongziSZHSHostResp)(nil),         // 10: go.BrTuitongziSZHSHostResp
	(*BrTuitongziSZHSLeaveReq)(nil),         // 11: go.BrTuitongziSZHSLeaveReq
	(*BrTuitongziSZHSLeaveResp)(nil),        // 12: go.BrTuitongziSZHSLeaveResp
	(*BrTuitongziSZHSOpenCardsReq)(nil),     // 13: go.BrTuitongziSZHSOpenCardsReq
	(*BrTuitongziSZHSOpenCardsResp)(nil),    // 14: go.BrTuitongziSZHSOpenCardsResp
	(*BrTuitongziSZHSControlReq)(nil),       // 15: go.BrTuitongziSZHSControlReq
	(*BrTuitongziSZHSControlResp)(nil),      // 16: go.BrTuitongziSZHSControlResp
	(*BrTuitongziSZHSSuperHostReq)(nil),     // 17: go.BrTuitongziSZHSSuperHostReq
	(*BrTuitongziSZHSSuperHostResp)(nil),    // 18: go.BrTuitongziSZHSSuperHostResp
	(*PlayerListInfo)(nil),                  // 19: go.PlayerListInfo
	(*TimeInfo)(nil),                        // 20: go.TimeInfo
	(*CardInfo)(nil),                        // 21: go.CardInfo
}
var file_brtuitongziSZHS_proto_depIdxs = []int32{
	19, // 0: go.BrTuitongziSZHSSceneResp.AllPlayers:type_name -> go.PlayerListInfo
	20, // 1: go.BrTuitongziSZHSStateStartResp.Times:type_name -> go.TimeInfo
	20, // 2: go.BrTuitongziSZHSStatePlayingResp.Times:type_name -> go.TimeInfo
	20, // 3: go.BrTuitongziSZHSStateOpenResp.Times:type_name -> go.TimeInfo
	7,  // 4: go.BrTuitongziSZHSStateOpenResp.OpenInfo:type_name -> go.BrTuitongziSZHSOpenResp
	20, // 5: go.BrTuitongziSZHSStateOverResp.Times:type_name -> go.TimeInfo
	21, // 6: go.BrTuitongziSZHSOpenResp.BankerCard:type_name -> go.CardInfo
	21, // 7: go.BrTuitongziSZHSOpenResp.ShunCard:type_name -> go.CardInfo
	21, // 8: go.BrTuitongziSZHSOpenResp.TianCard:type_name -> go.CardInfo
	21, // 9: go.BrTuitongziSZHSOpenResp.DiCard:type_name -> go.CardInfo
	7,  // 10: go.BrTuitongziSZHSOpenCardsResp.OpenInfo:type_name -> go.BrTuitongziSZHSOpenResp
	21, // 11: go.BrTuitongziSZHSControlReq.BankerCard:type_name -> go.CardInfo
	21, // 12: go.BrTuitongziSZHSControlReq.ShunCard:type_name -> go.CardInfo
	21, // 13: go.BrTuitongziSZHSControlReq.TianCard:type_name -> go.CardInfo
	21, // 14: go.BrTuitongziSZHSControlReq.DiCard:type_name -> go.CardInfo
	7,  // 15: go.BrTuitongziSZHSControlResp.OpenInfo:type_name -> go.BrTuitongziSZHSOpenResp
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_brtuitongziSZHS_proto_init() }
func file_brtuitongziSZHS_proto_init() {
	if File_brtuitongziSZHS_proto != nil {
		return
	}
	file_gamecomm_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_brtuitongziSZHS_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSSceneResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSStateStartResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSStatePlayingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSStateOpenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSStateOverResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSBetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSBetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSOpenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSCheckoutResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSHostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSHostResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSLeaveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSLeaveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSOpenCardsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSOpenCardsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSControlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSControlResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSSuperHostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brtuitongziSZHS_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrTuitongziSZHSSuperHostResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_brtuitongziSZHS_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_brtuitongziSZHS_proto_goTypes,
		DependencyIndexes: file_brtuitongziSZHS_proto_depIdxs,
		MessageInfos:      file_brtuitongziSZHS_proto_msgTypes,
	}.Build()
	File_brtuitongziSZHS_proto = out.File
	file_brtuitongziSZHS_proto_rawDesc = nil
	file_brtuitongziSZHS_proto_goTypes = nil
	file_brtuitongziSZHS_proto_depIdxs = nil
}
