// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: mahjongER.proto

package _go

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// kindID 3004
//二人麻将
////////////////////牌值定义/////////////////////////////
//		1 ~ 9 : 一万 ~ 9万
//		31 ~ 34 : 东、南、西、北风
//		41 : 发财
//		42 : 红中
//		43 : 白板
//		51 ~ 54 : 春夏秋冬
//		61 ~ 64 : 四种花色(梅兰竹菊)
/////////////////////玩家座位//////////////////////////////
//        骰子方位转换(弃用)
//    东 : 1,5,9  代表东
//    西 : 3,7,11 代表西
//    通过摸东、南、西、北风决定方位
/////////////////////风圈解义//////////////////////////////
// 一场麻将里有4个风圈（第一圈为东风圈、第二圈为南风圈、第三圈为西风圈、第四圈为北风圈）
// 每个风圈里有4局（第一局为东风局、第二局为南风局、第三局为西风局、第四局为北风局）
// 国标麻将，轮流坐庄，没有连续坐庄一说。
/////////////////////门风解义//////////////////////////////
// 门前发牌的那一家,门风为东，然后依照逆时钟方向计算
/////////////////////番型解义(请看文件末部)///////////////////
//刻子
type MahjongERKeZi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []int32   `protobuf:"varint,1,rep,packed,name=Cards,proto3" json:"Cards,omitempty"`
	Code  MJOperate `protobuf:"varint,2,opt,name=Code,proto3,enum=go.MJOperate" json:"Code,omitempty"`
	ByUid uint64    `protobuf:"varint,3,opt,name=ByUid,proto3" json:"ByUid,omitempty"` // 由谁提供
}

func (x *MahjongERKeZi) Reset() {
	*x = MahjongERKeZi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERKeZi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERKeZi) ProtoMessage() {}

func (x *MahjongERKeZi) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERKeZi.ProtoReflect.Descriptor instead.
func (*MahjongERKeZi) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{0}
}

func (x *MahjongERKeZi) GetCards() []int32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *MahjongERKeZi) GetCode() MJOperate {
	if x != nil {
		return x.Code
	}
	return MJOperate_NULL
}

func (x *MahjongERKeZi) GetByUid() uint64 {
	if x != nil {
		return x.ByUid
	}
	return 0
}

//提示
type MahjongERHint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  MJOperate `protobuf:"varint,1,opt,name=Code,proto3,enum=go.MJOperate" json:"Code,omitempty"` // 操作码
	Cards []int32   `protobuf:"varint,2,rep,packed,name=Cards,proto3" json:"Cards,omitempty"`          // 听哪几张牌| 胡牌和自摸皆为一张
	ByUid uint64    `protobuf:"varint,3,opt,name=ByUid,proto3" json:"ByUid,omitempty"`                 // 由谁提供
}

func (x *MahjongERHint) Reset() {
	*x = MahjongERHint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERHint) ProtoMessage() {}

func (x *MahjongERHint) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERHint.ProtoReflect.Descriptor instead.
func (*MahjongERHint) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{1}
}

func (x *MahjongERHint) GetCode() MJOperate {
	if x != nil {
		return x.Code
	}
	return MJOperate_NULL
}

func (x *MahjongERHint) GetCards() []int32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *MahjongERHint) GetByUid() uint64 {
	if x != nil {
		return x.ByUid
	}
	return 0
}

//麻将玩家信息
type MahjongERPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyInfo     *PlayerInfo      `protobuf:"bytes,1,opt,name=MyInfo,proto3" json:"MyInfo,omitempty"`                       //
	HandCards  []int32          `protobuf:"varint,2,rep,packed,name=HandCards,proto3" json:"HandCards,omitempty"`         //手牌
	KeZiCards  []*MahjongERKeZi `protobuf:"bytes,3,rep,name=KeZiCards,proto3" json:"KeZiCards,omitempty"`                 // 吃牌 桌牌:明在桌面上的牌,即碰、吃、杠后的牌
	TableCards []int32          `protobuf:"varint,4,rep,packed,name=TableCards,proto3" json:"TableCards,omitempty"`       //玩家的桌面牌值
	IsTing     bool             `protobuf:"varint,5,opt,name=IsTing,proto3" json:"IsTing,omitempty"`                      //是否听牌
	GainScore  int64            `protobuf:"varint,6,opt,name=GainScore,proto3" json:"GainScore,omitempty"`                //输赢分值
	TotalScore int64            `protobuf:"varint,7,opt,name=TotalScore,proto3" json:"TotalScore,omitempty"`              //总积分(当不为系统房时,该分值可以为负分)
	MenFeng    Direct           `protobuf:"varint,8,opt,name=MenFeng,proto3,enum=go.Direct" json:"MenFeng,omitempty"`     //门风(庄家==东风)
	SitDirect  Direct           `protobuf:"varint,9,opt,name=SitDirect,proto3,enum=go.Direct" json:"SitDirect,omitempty"` //座位方位
	OpHints    []*MahjongERHint `protobuf:"bytes,10,rep,name=OpHints,proto3" json:"OpHints,omitempty"`                    //玩家可操作(恢复场景)
}

func (x *MahjongERPlayer) Reset() {
	*x = MahjongERPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERPlayer) ProtoMessage() {}

func (x *MahjongERPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERPlayer.ProtoReflect.Descriptor instead.
func (*MahjongERPlayer) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{2}
}

func (x *MahjongERPlayer) GetMyInfo() *PlayerInfo {
	if x != nil {
		return x.MyInfo
	}
	return nil
}

func (x *MahjongERPlayer) GetHandCards() []int32 {
	if x != nil {
		return x.HandCards
	}
	return nil
}

func (x *MahjongERPlayer) GetKeZiCards() []*MahjongERKeZi {
	if x != nil {
		return x.KeZiCards
	}
	return nil
}

func (x *MahjongERPlayer) GetTableCards() []int32 {
	if x != nil {
		return x.TableCards
	}
	return nil
}

func (x *MahjongERPlayer) GetIsTing() bool {
	if x != nil {
		return x.IsTing
	}
	return false
}

func (x *MahjongERPlayer) GetGainScore() int64 {
	if x != nil {
		return x.GainScore
	}
	return 0
}

func (x *MahjongERPlayer) GetTotalScore() int64 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *MahjongERPlayer) GetMenFeng() Direct {
	if x != nil {
		return x.MenFeng
	}
	return Direct_Centre
}

func (x *MahjongERPlayer) GetSitDirect() Direct {
	if x != nil {
		return x.SitDirect
	}
	return Direct_Centre
}

func (x *MahjongERPlayer) GetOpHints() []*MahjongERHint {
	if x != nil {
		return x.OpHints
	}
	return nil
}

//入场
type EnterGameMJERResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameID   uint64           `protobuf:"varint,1,opt,name=GameID,proto3" json:"GameID,omitempty"`     //游戏标识
	ChairNum uint32           `protobuf:"varint,2,opt,name=ChairNum,proto3" json:"ChairNum,omitempty"` //椅子编号(不满足req的此项时,将由系统分配,并返回提示)
	Player   *MahjongERPlayer `protobuf:"bytes,3,opt,name=Player,proto3" json:"Player,omitempty"`
}

func (x *EnterGameMJERResp) Reset() {
	*x = EnterGameMJERResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterGameMJERResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGameMJERResp) ProtoMessage() {}

func (x *EnterGameMJERResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGameMJERResp.ProtoReflect.Descriptor instead.
func (*EnterGameMJERResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{3}
}

func (x *EnterGameMJERResp) GetGameID() uint64 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *EnterGameMJERResp) GetChairNum() uint32 {
	if x != nil {
		return x.ChairNum
	}
	return 0
}

func (x *EnterGameMJERResp) GetPlayer() *MahjongERPlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

//场景
type MahjongERSceneResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp   int64              `protobuf:"varint,1,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`              // 时间戳
	RunCount    int32              `protobuf:"varint,2,opt,name=RunCount,proto3" json:"RunCount,omitempty"`                // 当前局数
	RemainCount int32              `protobuf:"varint,3,opt,name=RemainCount,proto3" json:"RemainCount,omitempty"`          // 剩余张数
	BankerID    uint64             `protobuf:"varint,4,opt,name=BankerID,proto3" json:"BankerID,omitempty"`                // 庄家ID
	CurrentID   uint64             `protobuf:"varint,5,opt,name=CurrentID,proto3" json:"CurrentID,omitempty"`              // 当前玩家ID
	Inning      string             `protobuf:"bytes,6,opt,name=Inning,proto3" json:"Inning,omitempty"`                     // 牌局号
	HuCard      int32              `protobuf:"varint,7,opt,name=HuCard,proto3" json:"HuCard,omitempty"`                    // 胡牌,或自摸时的摸起的最后一张
	QuanFeng    Direct             `protobuf:"varint,8,opt,name=QuanFeng,proto3,enum=go.Direct" json:"QuanFeng,omitempty"` // 当前局的圈风
	AllPlayers  []*MahjongERPlayer `protobuf:"bytes,9,rep,name=AllPlayers,proto3" json:"AllPlayers,omitempty"`             //玩家列表(吃碰杠)
}

func (x *MahjongERSceneResp) Reset() {
	*x = MahjongERSceneResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERSceneResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERSceneResp) ProtoMessage() {}

func (x *MahjongERSceneResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERSceneResp.ProtoReflect.Descriptor instead.
func (*MahjongERSceneResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{4}
}

func (x *MahjongERSceneResp) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *MahjongERSceneResp) GetRunCount() int32 {
	if x != nil {
		return x.RunCount
	}
	return 0
}

func (x *MahjongERSceneResp) GetRemainCount() int32 {
	if x != nil {
		return x.RemainCount
	}
	return 0
}

func (x *MahjongERSceneResp) GetBankerID() uint64 {
	if x != nil {
		return x.BankerID
	}
	return 0
}

func (x *MahjongERSceneResp) GetCurrentID() uint64 {
	if x != nil {
		return x.CurrentID
	}
	return 0
}

func (x *MahjongERSceneResp) GetInning() string {
	if x != nil {
		return x.Inning
	}
	return ""
}

func (x *MahjongERSceneResp) GetHuCard() int32 {
	if x != nil {
		return x.HuCard
	}
	return 0
}

func (x *MahjongERSceneResp) GetQuanFeng() Direct {
	if x != nil {
		return x.QuanFeng
	}
	return Direct_Centre
}

func (x *MahjongERSceneResp) GetAllPlayers() []*MahjongERPlayer {
	if x != nil {
		return x.AllPlayers
	}
	return nil
}

//状态
// 服务端推送
//(空闲 - Free)
type MahjongERStateFreeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times  *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
	Inning string    `protobuf:"bytes,2,opt,name=Inning,proto3" json:"Inning,omitempty"` // 牌局号
}

func (x *MahjongERStateFreeResp) Reset() {
	*x = MahjongERStateFreeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERStateFreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERStateFreeResp) ProtoMessage() {}

func (x *MahjongERStateFreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERStateFreeResp.ProtoReflect.Descriptor instead.
func (*MahjongERStateFreeResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{5}
}

func (x *MahjongERStateFreeResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *MahjongERStateFreeResp) GetInning() string {
	if x != nil {
		return x.Inning
	}
	return ""
}

//方位 - Direct (调整座位:仅在第一局开始需决定所座方位,或座位替换新玩家)
type MahjongERStateDirectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times    *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
	MyDirect Direct    `protobuf:"varint,2,opt,name=MyDirect,proto3,enum=go.Direct" json:"MyDirect,omitempty"` //东南西北(系统决定)
}

func (x *MahjongERStateDirectResp) Reset() {
	*x = MahjongERStateDirectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERStateDirectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERStateDirectResp) ProtoMessage() {}

func (x *MahjongERStateDirectResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERStateDirectResp.ProtoReflect.Descriptor instead.
func (*MahjongERStateDirectResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{6}
}

func (x *MahjongERStateDirectResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *MahjongERStateDirectResp) GetMyDirect() Direct {
	if x != nil {
		return x.MyDirect
	}
	return Direct_Centre
}

//定庄 - Decide 系统定庄
type MahjongERStateDecideResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times    *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
	BankerID uint64    `protobuf:"varint,2,opt,name=BankerID,proto3" json:"BankerID,omitempty"`                // 首局默认座位东方的为庄家
	QuanFeng Direct    `protobuf:"varint,3,opt,name=QuanFeng,proto3,enum=go.Direct" json:"QuanFeng,omitempty"` // 当前局的圈风
	MenFeng  Direct    `protobuf:"varint,4,opt,name=MenFeng,proto3,enum=go.Direct" json:"MenFeng,omitempty"`   // 玩家的门风
}

func (x *MahjongERStateDecideResp) Reset() {
	*x = MahjongERStateDecideResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERStateDecideResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERStateDecideResp) ProtoMessage() {}

func (x *MahjongERStateDecideResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERStateDecideResp.ProtoReflect.Descriptor instead.
func (*MahjongERStateDecideResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{7}
}

func (x *MahjongERStateDecideResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *MahjongERStateDecideResp) GetBankerID() uint64 {
	if x != nil {
		return x.BankerID
	}
	return 0
}

func (x *MahjongERStateDecideResp) GetQuanFeng() Direct {
	if x != nil {
		return x.QuanFeng
	}
	return Direct_Centre
}

func (x *MahjongERStateDecideResp) GetMenFeng() Direct {
	if x != nil {
		return x.MenFeng
	}
	return Direct_Centre
}

//开始掷骰子 - RollDice 注:决定牌堆的起始位置
type MahjongERStateRollDiceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
}

func (x *MahjongERStateRollDiceResp) Reset() {
	*x = MahjongERStateRollDiceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERStateRollDiceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERStateRollDiceResp) ProtoMessage() {}

func (x *MahjongERStateRollDiceResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERStateRollDiceResp.ProtoReflect.Descriptor instead.
func (*MahjongERStateRollDiceResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{8}
}

func (x *MahjongERStateRollDiceResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

//(开始游戏) - Start
type MahjongERStateStartResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times    *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
	StartPos int32     `protobuf:"varint,2,opt,name=StartPos,proto3" json:"StartPos,omitempty"` //抓牌起始位置(即保留不抓取的牌墙)
}

func (x *MahjongERStateStartResp) Reset() {
	*x = MahjongERStateStartResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERStateStartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERStateStartResp) ProtoMessage() {}

func (x *MahjongERStateStartResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERStateStartResp.ProtoReflect.Descriptor instead.
func (*MahjongERStateStartResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{9}
}

func (x *MahjongERStateStartResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *MahjongERStateStartResp) GetStartPos() int32 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

//(游戏中) - Playing
type MahjongERStatePlayingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times  *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
	UserID uint64    `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"` // 轮到谁
	Card   int32     `protobuf:"varint,3,opt,name=Card,proto3" json:"Card,omitempty"`     // 只有UserID的玩家有牌值
}

func (x *MahjongERStatePlayingResp) Reset() {
	*x = MahjongERStatePlayingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERStatePlayingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERStatePlayingResp) ProtoMessage() {}

func (x *MahjongERStatePlayingResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERStatePlayingResp.ProtoReflect.Descriptor instead.
func (*MahjongERStatePlayingResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{10}
}

func (x *MahjongERStatePlayingResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *MahjongERStatePlayingResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *MahjongERStatePlayingResp) GetCard() int32 {
	if x != nil {
		return x.Card
	}
	return 0
}

//等待操作(仅对有提示的玩家提供)
type MahjongERStateWaitOperateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
}

func (x *MahjongERStateWaitOperateResp) Reset() {
	*x = MahjongERStateWaitOperateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERStateWaitOperateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERStateWaitOperateResp) ProtoMessage() {}

func (x *MahjongERStateWaitOperateResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERStateWaitOperateResp.ProtoReflect.Descriptor instead.
func (*MahjongERStateWaitOperateResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{11}
}

func (x *MahjongERStateWaitOperateResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

//(开奖) - Opening
type MahjongERStateOpenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times      *TimeInfo          `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
	IsFlow     bool               `protobuf:"varint,2,opt,name=IsFlow,proto3" json:"IsFlow,omitempty"`        // 是否流局
	HuCard     int32              `protobuf:"varint,3,opt,name=HuCard,proto3" json:"HuCard,omitempty"`        // 胡牌,或自摸时的摸起的最后一张
	WinnerID   uint64             `protobuf:"varint,4,opt,name=WinnerID,proto3" json:"WinnerID,omitempty"`    //胜利者ID（流局时为0）
	Fans       []byte             `protobuf:"bytes,5,opt,name=Fans,proto3" json:"Fans,omitempty"`             //番型列表 每个元素对应一个番型
	FanCount   int32              `protobuf:"varint,6,opt,name=FanCount,proto3" json:"FanCount,omitempty"`    //共计番数
	AllPlayers []*MahjongERPlayer `protobuf:"bytes,7,rep,name=AllPlayers,proto3" json:"AllPlayers,omitempty"` //所有玩家得分
}

func (x *MahjongERStateOpenResp) Reset() {
	*x = MahjongERStateOpenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERStateOpenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERStateOpenResp) ProtoMessage() {}

func (x *MahjongERStateOpenResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERStateOpenResp.ProtoReflect.Descriptor instead.
func (*MahjongERStateOpenResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{12}
}

func (x *MahjongERStateOpenResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *MahjongERStateOpenResp) GetIsFlow() bool {
	if x != nil {
		return x.IsFlow
	}
	return false
}

func (x *MahjongERStateOpenResp) GetHuCard() int32 {
	if x != nil {
		return x.HuCard
	}
	return 0
}

func (x *MahjongERStateOpenResp) GetWinnerID() uint64 {
	if x != nil {
		return x.WinnerID
	}
	return 0
}

func (x *MahjongERStateOpenResp) GetFans() []byte {
	if x != nil {
		return x.Fans
	}
	return nil
}

func (x *MahjongERStateOpenResp) GetFanCount() int32 {
	if x != nil {
		return x.FanCount
	}
	return 0
}

func (x *MahjongERStateOpenResp) GetAllPlayers() []*MahjongERPlayer {
	if x != nil {
		return x.AllPlayers
	}
	return nil
}

//(结束) - Over
type MahjongERStateOverResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
}

func (x *MahjongERStateOverResp) Reset() {
	*x = MahjongERStateOverResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERStateOverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERStateOverResp) ProtoMessage() {}

func (x *MahjongERStateOverResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERStateOverResp.ProtoReflect.Descriptor instead.
func (*MahjongERStateOverResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{13}
}

func (x *MahjongERStateOverResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

//////////////////////////////////////////////
//准备
type MahjongERReadyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsReady bool `protobuf:"varint,1,opt,name=IsReady,proto3" json:"IsReady,omitempty"` // 玩家准备，可以取消准备
}

func (x *MahjongERReadyReq) Reset() {
	*x = MahjongERReadyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERReadyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERReadyReq) ProtoMessage() {}

func (x *MahjongERReadyReq) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERReadyReq.ProtoReflect.Descriptor instead.
func (*MahjongERReadyReq) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{14}
}

func (x *MahjongERReadyReq) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type MahjongERReadyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID  uint64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	IsReady bool   `protobuf:"varint,2,opt,name=IsReady,proto3" json:"IsReady,omitempty"` // 玩家准备，可以取消准备
}

func (x *MahjongERReadyResp) Reset() {
	*x = MahjongERReadyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERReadyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERReadyResp) ProtoMessage() {}

func (x *MahjongERReadyResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERReadyResp.ProtoReflect.Descriptor instead.
func (*MahjongERReadyResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{15}
}

func (x *MahjongERReadyResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *MahjongERReadyResp) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

//
//庄家扔骰子
type MahjongERRollReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MahjongERRollReq) Reset() {
	*x = MahjongERRollReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERRollReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERRollReq) ProtoMessage() {}

func (x *MahjongERRollReq) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERRollReq.ProtoReflect.Descriptor instead.
func (*MahjongERRollReq) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{16}
}

type MahjongERRollResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Dice   []byte `protobuf:"bytes,2,opt,name=Dice,proto3" json:"Dice,omitempty"` //骰子决定,起抓牌位置
}

func (x *MahjongERRollResp) Reset() {
	*x = MahjongERRollResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERRollResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERRollResp) ProtoMessage() {}

func (x *MahjongERRollResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERRollResp.ProtoReflect.Descriptor instead.
func (*MahjongERRollResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{17}
}

func (x *MahjongERRollResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *MahjongERRollResp) GetDice() []byte {
	if x != nil {
		return x.Dice
	}
	return nil
}

// 玩家打出去的牌
type MahjongEROutCardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card int32 `protobuf:"varint,1,opt,name=Card,proto3" json:"Card,omitempty"` //
}

func (x *MahjongEROutCardReq) Reset() {
	*x = MahjongEROutCardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongEROutCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongEROutCardReq) ProtoMessage() {}

func (x *MahjongEROutCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongEROutCardReq.ProtoReflect.Descriptor instead.
func (*MahjongEROutCardReq) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{18}
}

func (x *MahjongEROutCardReq) GetCard() int32 {
	if x != nil {
		return x.Card
	}
	return 0
}

type MahjongEROutCardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"` // 玩家ID
	Card   int32  `protobuf:"varint,2,opt,name=Card,proto3" json:"Card,omitempty"`     //
}

func (x *MahjongEROutCardResp) Reset() {
	*x = MahjongEROutCardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongEROutCardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongEROutCardResp) ProtoMessage() {}

func (x *MahjongEROutCardResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongEROutCardResp.ProtoReflect.Descriptor instead.
func (*MahjongEROutCardResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{19}
}

func (x *MahjongEROutCardResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *MahjongEROutCardResp) GetCard() int32 {
	if x != nil {
		return x.Card
	}
	return 0
}

// 操作
type MahjongEROperateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  MJOperate `protobuf:"varint,1,opt,name=Code,proto3,enum=go.MJOperate" json:"Code,omitempty"` // 操作码 pass表示弃牌
	Cards []int32   `protobuf:"varint,2,rep,packed,name=Cards,proto3" json:"Cards,omitempty"`          // 吃|碰|杠 时的手牌
}

func (x *MahjongEROperateReq) Reset() {
	*x = MahjongEROperateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongEROperateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongEROperateReq) ProtoMessage() {}

func (x *MahjongEROperateReq) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongEROperateReq.ProtoReflect.Descriptor instead.
func (*MahjongEROperateReq) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{20}
}

func (x *MahjongEROperateReq) GetCode() MJOperate {
	if x != nil {
		return x.Code
	}
	return MJOperate_NULL
}

func (x *MahjongEROperateReq) GetCards() []int32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

type MahjongEROperateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`               // 玩家ID
	Code   MJOperate `protobuf:"varint,2,opt,name=Code,proto3,enum=go.MJOperate" json:"Code,omitempty"` // 操作码
	Cards  []int32   `protobuf:"varint,3,rep,packed,name=Cards,proto3" json:"Cards,omitempty"`          // 吃|碰|杠 时的组合牌
}

func (x *MahjongEROperateResp) Reset() {
	*x = MahjongEROperateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongEROperateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongEROperateResp) ProtoMessage() {}

func (x *MahjongEROperateResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongEROperateResp.ProtoReflect.Descriptor instead.
func (*MahjongEROperateResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{21}
}

func (x *MahjongEROperateResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *MahjongEROperateResp) GetCode() MJOperate {
	if x != nil {
		return x.Code
	}
	return MJOperate_NULL
}

func (x *MahjongEROperateResp) GetCards() []int32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

////////////////////////////////
//
//发牌
type MahjongERDealResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID    uint64  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`              // 玩家ID
	CurPos    int32   `protobuf:"varint,2,opt,name=CurPos,proto3" json:"CurPos,omitempty"`              // 抓牌起始位置
	HandCards []int32 `protobuf:"varint,3,rep,packed,name=HandCards,proto3" json:"HandCards,omitempty"` // 玩家的手牌(座位上的玩家才有,且只能拿到自己的牌值)
}

func (x *MahjongERDealResp) Reset() {
	*x = MahjongERDealResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERDealResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERDealResp) ProtoMessage() {}

func (x *MahjongERDealResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERDealResp.ProtoReflect.Descriptor instead.
func (*MahjongERDealResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{22}
}

func (x *MahjongERDealResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *MahjongERDealResp) GetCurPos() int32 {
	if x != nil {
		return x.CurPos
	}
	return 0
}

func (x *MahjongERDealResp) GetHandCards() []int32 {
	if x != nil {
		return x.HandCards
	}
	return nil
}

//
// 玩家只能收到自己的
type MahjongERHintResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64           `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"` // 玩家ID
	Hints  []*MahjongERHint `protobuf:"bytes,2,rep,name=Hints,proto3" json:"Hints,omitempty"`    //提示 注意:吃牌时,有多种组合 cards仅提供玩家手牌牌值
}

func (x *MahjongERHintResp) Reset() {
	*x = MahjongERHintResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mahjongER_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MahjongERHintResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MahjongERHintResp) ProtoMessage() {}

func (x *MahjongERHintResp) ProtoReflect() protoreflect.Message {
	mi := &file_mahjongER_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MahjongERHintResp.ProtoReflect.Descriptor instead.
func (*MahjongERHintResp) Descriptor() ([]byte, []int) {
	return file_mahjongER_proto_rawDescGZIP(), []int{23}
}

func (x *MahjongERHintResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *MahjongERHintResp) GetHints() []*MahjongERHint {
	if x != nil {
		return x.Hints
	}
	return nil
}

var File_mahjongER_proto protoreflect.FileDescriptor

var file_mahjongER_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x67, 0x6f, 0x1a, 0x0e, 0x67, 0x61, 0x6d, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5e, 0x0a, 0x0d, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67,
	0x45, 0x52, 0x4b, 0x65, 0x5a, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x21, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x67, 0x6f, 0x2e,
	0x4d, 0x4a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x42, 0x79, 0x55, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x42, 0x79, 0x55, 0x69, 0x64, 0x22, 0x5e, 0x0a, 0x0d, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67,
	0x45, 0x52, 0x48, 0x69, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x67, 0x6f, 0x2e, 0x4d, 0x4a, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x61, 0x72,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x42, 0x79, 0x55, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x42, 0x79, 0x55, 0x69, 0x64, 0x22, 0xfb, 0x02, 0x0a, 0x0f, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e,
	0x67, 0x45, 0x52, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x06, 0x4d, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x4d, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x48, 0x61, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x48, 0x61, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12,
	0x2f, 0x0a, 0x09, 0x4b, 0x65, 0x5a, 0x69, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x2e, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45,
	0x52, 0x4b, 0x65, 0x5a, 0x69, 0x52, 0x09, 0x4b, 0x65, 0x5a, 0x69, 0x43, 0x61, 0x72, 0x64, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x61, 0x72, 0x64, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x54, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x49, 0x73, 0x54, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x61, 0x69, 0x6e,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x47, 0x61, 0x69,
	0x6e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x24, 0x0a, 0x07, 0x4d, 0x65, 0x6e, 0x46, 0x65, 0x6e,
	0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x67, 0x6f, 0x2e, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x52, 0x07, 0x4d, 0x65, 0x6e, 0x46, 0x65, 0x6e, 0x67, 0x12, 0x28, 0x0a, 0x09,
	0x53, 0x69, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0a, 0x2e, 0x67, 0x6f, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x09, 0x53, 0x69, 0x74,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x4f, 0x70, 0x48, 0x69, 0x6e, 0x74,
	0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x2e, 0x4d, 0x61, 0x68,
	0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x48, 0x69, 0x6e, 0x74, 0x52, 0x07, 0x4f, 0x70, 0x48, 0x69,
	0x6e, 0x74, 0x73, 0x22, 0x74, 0x0a, 0x11, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65,
	0x4d, 0x4a, 0x45, 0x52, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x69, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x43, 0x68, 0x61, 0x69, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x2b, 0x0a, 0x06,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67,
	0x6f, 0x2e, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0xb7, 0x02, 0x0a, 0x12, 0x4d, 0x61,
	0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a,
	0x0a, 0x08, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65,
	0x6d, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x42, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x42, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x6e, 0x6e, 0x69, 0x6e, 0x67,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x16,
	0x0a, 0x06, 0x48, 0x75, 0x43, 0x61, 0x72, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x48, 0x75, 0x43, 0x61, 0x72, 0x64, 0x12, 0x26, 0x0a, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x46, 0x65,
	0x6e, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x67, 0x6f, 0x2e, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x52, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x46, 0x65, 0x6e, 0x67, 0x12, 0x33,
	0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x09, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x6f, 0x2e, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45,
	0x52, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0a, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x22, 0x54, 0x0a, 0x16, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x46, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a,
	0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67,
	0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x49, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x66, 0x0a, 0x18, 0x4d, 0x61, 0x68,
	0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x08, 0x4d, 0x79, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x67, 0x6f,
	0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x08, 0x4d, 0x79, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x22, 0xa8, 0x01, 0x0a, 0x18, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x44, 0x65, 0x63, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22,
	0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x42, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x49, 0x44, 0x12, 0x26,
	0x0a, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x46, 0x65, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0a, 0x2e, 0x67, 0x6f, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x08, 0x51, 0x75,
	0x61, 0x6e, 0x46, 0x65, 0x6e, 0x67, 0x12, 0x24, 0x0a, 0x07, 0x4d, 0x65, 0x6e, 0x46, 0x65, 0x6e,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x67, 0x6f, 0x2e, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x52, 0x07, 0x4d, 0x65, 0x6e, 0x46, 0x65, 0x6e, 0x67, 0x22, 0x40, 0x0a, 0x1a,
	0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6c, 0x6c, 0x44, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x59,
	0x0a, 0x17, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x22, 0x6b, 0x0a, 0x19, 0x4d, 0x61, 0x68,
	0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x43, 0x61, 0x72, 0x64, 0x22, 0x43, 0x0a, 0x1d, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e,
	0x67, 0x45, 0x52, 0x53, 0x74, 0x61, 0x74, 0x65, 0x57, 0x61, 0x69, 0x74, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22, 0xed, 0x01, 0x0a, 0x16,
	0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4f, 0x70,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73,
	0x46, 0x6c, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x49, 0x73, 0x46, 0x6c,
	0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x75, 0x43, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x48, 0x75, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x57, 0x69,
	0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x57, 0x69,
	0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x61, 0x6e, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x46, 0x61, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x61,
	0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x46, 0x61,
	0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x6f, 0x2e,
	0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x0a, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x3c, 0x0a, 0x16, 0x4d,
	0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4f, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x2d, 0x0a, 0x11, 0x4d, 0x61, 0x68,
	0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x22, 0x46, 0x0a, 0x12, 0x4d, 0x61, 0x68, 0x6a,
	0x6f, 0x6e, 0x67, 0x45, 0x52, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x22, 0x12, 0x0a, 0x10, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x52, 0x6f, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x22, 0x3f, 0x0a, 0x11, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45,
	0x52, 0x52, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x44, 0x69, 0x63, 0x65, 0x22, 0x29, 0x0a, 0x13, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67,
	0x45, 0x52, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x61, 0x72, 0x64,
	0x22, 0x42, 0x0a, 0x14, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x4f, 0x75, 0x74,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x43, 0x61, 0x72, 0x64, 0x22, 0x4e, 0x0a, 0x13, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45,
	0x52, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x67, 0x6f, 0x2e, 0x4d,
	0x4a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x43,
	0x61, 0x72, 0x64, 0x73, 0x22, 0x67, 0x0a, 0x14, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45,
	0x52, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x21, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x67, 0x6f, 0x2e, 0x4d, 0x4a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x22, 0x61, 0x0a,
	0x11, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x44, 0x65, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x75,
	0x72, 0x50, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x43, 0x75, 0x72, 0x50,
	0x6f, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x48, 0x61, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x48, 0x61, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73,
	0x22, 0x54, 0x0a, 0x11, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x48, 0x69, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x27, 0x0a,
	0x05, 0x48, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67,
	0x6f, 0x2e, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x45, 0x52, 0x48, 0x69, 0x6e, 0x74, 0x52,
	0x05, 0x48, 0x69, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mahjongER_proto_rawDescOnce sync.Once
	file_mahjongER_proto_rawDescData = file_mahjongER_proto_rawDesc
)

func file_mahjongER_proto_rawDescGZIP() []byte {
	file_mahjongER_proto_rawDescOnce.Do(func() {
		file_mahjongER_proto_rawDescData = protoimpl.X.CompressGZIP(file_mahjongER_proto_rawDescData)
	})
	return file_mahjongER_proto_rawDescData
}

var file_mahjongER_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_mahjongER_proto_goTypes = []interface{}{
	(*MahjongERKeZi)(nil),                 // 0: go.MahjongERKeZi
	(*MahjongERHint)(nil),                 // 1: go.MahjongERHint
	(*MahjongERPlayer)(nil),               // 2: go.MahjongERPlayer
	(*EnterGameMJERResp)(nil),             // 3: go.EnterGameMJERResp
	(*MahjongERSceneResp)(nil),            // 4: go.MahjongERSceneResp
	(*MahjongERStateFreeResp)(nil),        // 5: go.MahjongERStateFreeResp
	(*MahjongERStateDirectResp)(nil),      // 6: go.MahjongERStateDirectResp
	(*MahjongERStateDecideResp)(nil),      // 7: go.MahjongERStateDecideResp
	(*MahjongERStateRollDiceResp)(nil),    // 8: go.MahjongERStateRollDiceResp
	(*MahjongERStateStartResp)(nil),       // 9: go.MahjongERStateStartResp
	(*MahjongERStatePlayingResp)(nil),     // 10: go.MahjongERStatePlayingResp
	(*MahjongERStateWaitOperateResp)(nil), // 11: go.MahjongERStateWaitOperateResp
	(*MahjongERStateOpenResp)(nil),        // 12: go.MahjongERStateOpenResp
	(*MahjongERStateOverResp)(nil),        // 13: go.MahjongERStateOverResp
	(*MahjongERReadyReq)(nil),             // 14: go.MahjongERReadyReq
	(*MahjongERReadyResp)(nil),            // 15: go.MahjongERReadyResp
	(*MahjongERRollReq)(nil),              // 16: go.MahjongERRollReq
	(*MahjongERRollResp)(nil),             // 17: go.MahjongERRollResp
	(*MahjongEROutCardReq)(nil),           // 18: go.MahjongEROutCardReq
	(*MahjongEROutCardResp)(nil),          // 19: go.MahjongEROutCardResp
	(*MahjongEROperateReq)(nil),           // 20: go.MahjongEROperateReq
	(*MahjongEROperateResp)(nil),          // 21: go.MahjongEROperateResp
	(*MahjongERDealResp)(nil),             // 22: go.MahjongERDealResp
	(*MahjongERHintResp)(nil),             // 23: go.MahjongERHintResp
	(MJOperate)(0),                        // 24: go.MJOperate
	(*PlayerInfo)(nil),                    // 25: go.PlayerInfo
	(Direct)(0),                           // 26: go.Direct
	(*TimeInfo)(nil),                      // 27: go.TimeInfo
}
var file_mahjongER_proto_depIdxs = []int32{
	24, // 0: go.MahjongERKeZi.Code:type_name -> go.MJOperate
	24, // 1: go.MahjongERHint.Code:type_name -> go.MJOperate
	25, // 2: go.MahjongERPlayer.MyInfo:type_name -> go.PlayerInfo
	0,  // 3: go.MahjongERPlayer.KeZiCards:type_name -> go.MahjongERKeZi
	26, // 4: go.MahjongERPlayer.MenFeng:type_name -> go.Direct
	26, // 5: go.MahjongERPlayer.SitDirect:type_name -> go.Direct
	1,  // 6: go.MahjongERPlayer.OpHints:type_name -> go.MahjongERHint
	2,  // 7: go.EnterGameMJERResp.Player:type_name -> go.MahjongERPlayer
	26, // 8: go.MahjongERSceneResp.QuanFeng:type_name -> go.Direct
	2,  // 9: go.MahjongERSceneResp.AllPlayers:type_name -> go.MahjongERPlayer
	27, // 10: go.MahjongERStateFreeResp.Times:type_name -> go.TimeInfo
	27, // 11: go.MahjongERStateDirectResp.Times:type_name -> go.TimeInfo
	26, // 12: go.MahjongERStateDirectResp.MyDirect:type_name -> go.Direct
	27, // 13: go.MahjongERStateDecideResp.Times:type_name -> go.TimeInfo
	26, // 14: go.MahjongERStateDecideResp.QuanFeng:type_name -> go.Direct
	26, // 15: go.MahjongERStateDecideResp.MenFeng:type_name -> go.Direct
	27, // 16: go.MahjongERStateRollDiceResp.Times:type_name -> go.TimeInfo
	27, // 17: go.MahjongERStateStartResp.Times:type_name -> go.TimeInfo
	27, // 18: go.MahjongERStatePlayingResp.Times:type_name -> go.TimeInfo
	27, // 19: go.MahjongERStateWaitOperateResp.Times:type_name -> go.TimeInfo
	27, // 20: go.MahjongERStateOpenResp.Times:type_name -> go.TimeInfo
	2,  // 21: go.MahjongERStateOpenResp.AllPlayers:type_name -> go.MahjongERPlayer
	27, // 22: go.MahjongERStateOverResp.Times:type_name -> go.TimeInfo
	24, // 23: go.MahjongEROperateReq.Code:type_name -> go.MJOperate
	24, // 24: go.MahjongEROperateResp.Code:type_name -> go.MJOperate
	1,  // 25: go.MahjongERHintResp.Hints:type_name -> go.MahjongERHint
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_mahjongER_proto_init() }
func file_mahjongER_proto_init() {
	if File_mahjongER_proto != nil {
		return
	}
	file_gamecomm_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mahjongER_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERKeZi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERHint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterGameMJERResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERSceneResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERStateFreeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERStateDirectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERStateDecideResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERStateRollDiceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERStateStartResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERStatePlayingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERStateWaitOperateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERStateOpenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERStateOverResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERReadyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERReadyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERRollReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERRollResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongEROutCardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongEROutCardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongEROperateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongEROperateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERDealResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mahjongER_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MahjongERHintResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mahjongER_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mahjongER_proto_goTypes,
		DependencyIndexes: file_mahjongER_proto_depIdxs,
		MessageInfos:      file_mahjongER_proto_msgTypes,
	}.Build()
	File_mahjongER_proto = out.File
	file_mahjongER_proto_rawDesc = nil
	file_mahjongER_proto_goTypes = nil
	file_mahjongER_proto_depIdxs = nil
}
