// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: qzcowcow.proto

package _go

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// kindID 1004
//抢庄牛牛玩家信息
type QzcowcowPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyInfo     *PlayerInfo `protobuf:"bytes,1,opt,name=MyInfo,proto3" json:"MyInfo,omitempty"`
	Cards      *CardInfo   `protobuf:"bytes,2,opt,name=Cards,proto3" json:"Cards,omitempty"`            //
	CallScore  int64       `protobuf:"varint,3,opt,name=CallScore,proto3" json:"CallScore,omitempty"`   //叫分分值
	BetScore   int64       `protobuf:"varint,4,opt,name=BetScore,proto3" json:"BetScore,omitempty"`     //下注分值
	GainScore  int64       `protobuf:"varint,5,opt,name=GainScore,proto3" json:"GainScore,omitempty"`   //输赢分值
	TotalScore int64       `protobuf:"varint,6,opt,name=TotalScore,proto3" json:"TotalScore,omitempty"` //总积分
}

func (x *QzcowcowPlayer) Reset() {
	*x = QzcowcowPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowPlayer) ProtoMessage() {}

func (x *QzcowcowPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowPlayer.ProtoReflect.Descriptor instead.
func (*QzcowcowPlayer) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{0}
}

func (x *QzcowcowPlayer) GetMyInfo() *PlayerInfo {
	if x != nil {
		return x.MyInfo
	}
	return nil
}

func (x *QzcowcowPlayer) GetCards() *CardInfo {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *QzcowcowPlayer) GetCallScore() int64 {
	if x != nil {
		return x.CallScore
	}
	return 0
}

func (x *QzcowcowPlayer) GetBetScore() int64 {
	if x != nil {
		return x.BetScore
	}
	return 0
}

func (x *QzcowcowPlayer) GetGainScore() int64 {
	if x != nil {
		return x.GainScore
	}
	return 0
}

func (x *QzcowcowPlayer) GetTotalScore() int64 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

//入场
type EnterGameQZCCResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameID   uint64          `protobuf:"varint,1,opt,name=GameID,proto3" json:"GameID,omitempty"`     //游戏标识
	ChairNum uint32          `protobuf:"varint,2,opt,name=ChairNum,proto3" json:"ChairNum,omitempty"` //椅子编号(不满足req的此项时,将由系统分配,并返回提示)
	Player   *QzcowcowPlayer `protobuf:"bytes,3,opt,name=Player,proto3" json:"Player,omitempty"`
}

func (x *EnterGameQZCCResp) Reset() {
	*x = EnterGameQZCCResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterGameQZCCResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGameQZCCResp) ProtoMessage() {}

func (x *EnterGameQZCCResp) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGameQZCCResp.ProtoReflect.Descriptor instead.
func (*EnterGameQZCCResp) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{1}
}

func (x *EnterGameQZCCResp) GetGameID() uint64 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *EnterGameQZCCResp) GetChairNum() uint32 {
	if x != nil {
		return x.ChairNum
	}
	return 0
}

func (x *EnterGameQZCCResp) GetPlayer() *QzcowcowPlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

//场景
type QzcowcowSceneResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp  int64             `protobuf:"varint,1,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`  //时间戳
	Chips      []int32           `protobuf:"varint,2,rep,packed,name=Chips,proto3" json:"Chips,omitempty"`   //筹码
	Inning     string            `protobuf:"bytes,3,opt,name=Inning,proto3" json:"Inning,omitempty"`         // 牌局号
	AllPlayers []*QzcowcowPlayer `protobuf:"bytes,4,rep,name=AllPlayers,proto3" json:"AllPlayers,omitempty"` //玩家列表信息
	HostID     uint64            `protobuf:"varint,5,opt,name=HostID,proto3" json:"HostID,omitempty"`        //庄家ID
}

func (x *QzcowcowSceneResp) Reset() {
	*x = QzcowcowSceneResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowSceneResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowSceneResp) ProtoMessage() {}

func (x *QzcowcowSceneResp) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowSceneResp.ProtoReflect.Descriptor instead.
func (*QzcowcowSceneResp) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{2}
}

func (x *QzcowcowSceneResp) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *QzcowcowSceneResp) GetChips() []int32 {
	if x != nil {
		return x.Chips
	}
	return nil
}

func (x *QzcowcowSceneResp) GetInning() string {
	if x != nil {
		return x.Inning
	}
	return ""
}

func (x *QzcowcowSceneResp) GetAllPlayers() []*QzcowcowPlayer {
	if x != nil {
		return x.AllPlayers
	}
	return nil
}

func (x *QzcowcowSceneResp) GetHostID() uint64 {
	if x != nil {
		return x.HostID
	}
	return 0
}

//状态
// 服务端推送
//(空闲 - )
type QzcowcowStateFreeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times  *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
	Inning string    `protobuf:"bytes,2,opt,name=Inning,proto3" json:"Inning,omitempty"` // 牌局号
}

func (x *QzcowcowStateFreeResp) Reset() {
	*x = QzcowcowStateFreeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowStateFreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowStateFreeResp) ProtoMessage() {}

func (x *QzcowcowStateFreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowStateFreeResp.ProtoReflect.Descriptor instead.
func (*QzcowcowStateFreeResp) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{3}
}

func (x *QzcowcowStateFreeResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *QzcowcowStateFreeResp) GetInning() string {
	if x != nil {
		return x.Inning
	}
	return ""
}

//(开始 - 喊庄)
type QzcowcowStateCallResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
}

func (x *QzcowcowStateCallResp) Reset() {
	*x = QzcowcowStateCallResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowStateCallResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowStateCallResp) ProtoMessage() {}

func (x *QzcowcowStateCallResp) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowStateCallResp.ProtoReflect.Descriptor instead.
func (*QzcowcowStateCallResp) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{4}
}

func (x *QzcowcowStateCallResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

//定庄
type QzcowcowStateDecideResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times    *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
	HostID   uint64    `protobuf:"varint,2,opt,name=HostID,proto3" json:"HostID,omitempty"`
	Multiple int64     `protobuf:"varint,3,opt,name=Multiple,proto3" json:"Multiple,omitempty"` //相同倍数 可用作
}

func (x *QzcowcowStateDecideResp) Reset() {
	*x = QzcowcowStateDecideResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowStateDecideResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowStateDecideResp) ProtoMessage() {}

func (x *QzcowcowStateDecideResp) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowStateDecideResp.ProtoReflect.Descriptor instead.
func (*QzcowcowStateDecideResp) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{5}
}

func (x *QzcowcowStateDecideResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *QzcowcowStateDecideResp) GetHostID() uint64 {
	if x != nil {
		return x.HostID
	}
	return 0
}

func (x *QzcowcowStateDecideResp) GetMultiple() int64 {
	if x != nil {
		return x.Multiple
	}
	return 0
}

//(游戏中 - 下注)
type QzcowcowStatePlayingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
}

func (x *QzcowcowStatePlayingResp) Reset() {
	*x = QzcowcowStatePlayingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowStatePlayingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowStatePlayingResp) ProtoMessage() {}

func (x *QzcowcowStatePlayingResp) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowStatePlayingResp.ProtoReflect.Descriptor instead.
func (*QzcowcowStatePlayingResp) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{6}
}

func (x *QzcowcowStatePlayingResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

//(发牌)
type QzcowcowStateDealResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
}

func (x *QzcowcowStateDealResp) Reset() {
	*x = QzcowcowStateDealResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowStateDealResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowStateDealResp) ProtoMessage() {}

func (x *QzcowcowStateDealResp) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowStateDealResp.ProtoReflect.Descriptor instead.
func (*QzcowcowStateDealResp) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{7}
}

func (x *QzcowcowStateDealResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

//(开奖 -- 比牌结果)
type QzcowcowStateOpenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times    *TimeInfo         `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
	OpenInfo *QzcowcowOpenResp `protobuf:"bytes,2,opt,name=OpenInfo,proto3" json:"OpenInfo,omitempty"`
}

func (x *QzcowcowStateOpenResp) Reset() {
	*x = QzcowcowStateOpenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowStateOpenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowStateOpenResp) ProtoMessage() {}

func (x *QzcowcowStateOpenResp) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowStateOpenResp.ProtoReflect.Descriptor instead.
func (*QzcowcowStateOpenResp) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{8}
}

func (x *QzcowcowStateOpenResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *QzcowcowStateOpenResp) GetOpenInfo() *QzcowcowOpenResp {
	if x != nil {
		return x.OpenInfo
	}
	return nil
}

//(结束)
type QzcowcowStateOverResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
}

func (x *QzcowcowStateOverResp) Reset() {
	*x = QzcowcowStateOverResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowStateOverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowStateOverResp) ProtoMessage() {}

func (x *QzcowcowStateOverResp) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowStateOverResp.ProtoReflect.Descriptor instead.
func (*QzcowcowStateOverResp) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{9}
}

func (x *QzcowcowStateOverResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

//////////有些玩家不配有牌////////
type QzcowcowDealResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Cards  *CardInfo `protobuf:"bytes,2,opt,name=Cards,proto3" json:"Cards,omitempty"` //只有开奖时有真实值
}

func (x *QzcowcowDealResp) Reset() {
	*x = QzcowcowDealResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowDealResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowDealResp) ProtoMessage() {}

func (x *QzcowcowDealResp) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowDealResp.ProtoReflect.Descriptor instead.
func (*QzcowcowDealResp) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{10}
}

func (x *QzcowcowDealResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *QzcowcowDealResp) GetCards() *CardInfo {
	if x != nil {
		return x.Cards
	}
	return nil
}

//////////////////////////////////////
//准备
type QzcowcowReadyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsReady bool `protobuf:"varint,1,opt,name=IsReady,proto3" json:"IsReady,omitempty"` // 玩家准备，可以取消准备
}

func (x *QzcowcowReadyReq) Reset() {
	*x = QzcowcowReadyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowReadyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowReadyReq) ProtoMessage() {}

func (x *QzcowcowReadyReq) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowReadyReq.ProtoReflect.Descriptor instead.
func (*QzcowcowReadyReq) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{11}
}

func (x *QzcowcowReadyReq) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type QzcowcowReadyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID  uint64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	IsReady bool   `protobuf:"varint,2,opt,name=IsReady,proto3" json:"IsReady,omitempty"` // 玩家准备，可以取消准备
}

func (x *QzcowcowReadyResp) Reset() {
	*x = QzcowcowReadyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowReadyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowReadyResp) ProtoMessage() {}

func (x *QzcowcowReadyResp) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowReadyResp.ProtoReflect.Descriptor instead.
func (*QzcowcowReadyResp) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{12}
}

func (x *QzcowcowReadyResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *QzcowcowReadyResp) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

//喊庄
type QzcowcowCallReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Multiple int64 `protobuf:"varint,1,opt,name=Multiple,proto3" json:"Multiple,omitempty"` //喊庄倍数
}

func (x *QzcowcowCallReq) Reset() {
	*x = QzcowcowCallReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowCallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowCallReq) ProtoMessage() {}

func (x *QzcowcowCallReq) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowCallReq.ProtoReflect.Descriptor instead.
func (*QzcowcowCallReq) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{13}
}

func (x *QzcowcowCallReq) GetMultiple() int64 {
	if x != nil {
		return x.Multiple
	}
	return 0
}

type QzcowcowCallResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   uint64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Multiple int64  `protobuf:"varint,2,opt,name=Multiple,proto3" json:"Multiple,omitempty"` //喊庄倍数
}

func (x *QzcowcowCallResp) Reset() {
	*x = QzcowcowCallResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowCallResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowCallResp) ProtoMessage() {}

func (x *QzcowcowCallResp) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowCallResp.ProtoReflect.Descriptor instead.
func (*QzcowcowCallResp) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{14}
}

func (x *QzcowcowCallResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *QzcowcowCallResp) GetMultiple() int64 {
	if x != nil {
		return x.Multiple
	}
	return 0
}

//下注
type QzcowcowBetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BetArea  int32 `protobuf:"varint,1,opt,name=BetArea,proto3" json:"BetArea,omitempty"`   //下注区域
	BetScore int64 `protobuf:"varint,2,opt,name=BetScore,proto3" json:"BetScore,omitempty"` //倍数
}

func (x *QzcowcowBetReq) Reset() {
	*x = QzcowcowBetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowBetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowBetReq) ProtoMessage() {}

func (x *QzcowcowBetReq) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowBetReq.ProtoReflect.Descriptor instead.
func (*QzcowcowBetReq) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{15}
}

func (x *QzcowcowBetReq) GetBetArea() int32 {
	if x != nil {
		return x.BetArea
	}
	return 0
}

func (x *QzcowcowBetReq) GetBetScore() int64 {
	if x != nil {
		return x.BetScore
	}
	return 0
}

//下注结果：广播
type QzcowcowBetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   uint64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BetArea  int32  `protobuf:"varint,2,opt,name=BetArea,proto3" json:"BetArea,omitempty"`   //下注区域
	BetScore int64  `protobuf:"varint,3,opt,name=BetScore,proto3" json:"BetScore,omitempty"` //倍数
}

func (x *QzcowcowBetResp) Reset() {
	*x = QzcowcowBetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowBetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowBetResp) ProtoMessage() {}

func (x *QzcowcowBetResp) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowBetResp.ProtoReflect.Descriptor instead.
func (*QzcowcowBetResp) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{16}
}

func (x *QzcowcowBetResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *QzcowcowBetResp) GetBetArea() int32 {
	if x != nil {
		return x.BetArea
	}
	return 0
}

func (x *QzcowcowBetResp) GetBetScore() int64 {
	if x != nil {
		return x.BetScore
	}
	return 0
}

//开牌
type QzcowcowOpenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllPlayers []*QzcowcowPlayer `protobuf:"bytes,1,rep,name=AllPlayers,proto3" json:"AllPlayers,omitempty"` //玩家列表信息
}

func (x *QzcowcowOpenResp) Reset() {
	*x = QzcowcowOpenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowOpenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowOpenResp) ProtoMessage() {}

func (x *QzcowcowOpenResp) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowOpenResp.ProtoReflect.Descriptor instead.
func (*QzcowcowOpenResp) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{17}
}

func (x *QzcowcowOpenResp) GetAllPlayers() []*QzcowcowPlayer {
	if x != nil {
		return x.AllPlayers
	}
	return nil
}

//结算
type QzcowcowOverResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllPlayers []*QzcowcowPlayer `protobuf:"bytes,1,rep,name=AllPlayers,proto3" json:"AllPlayers,omitempty"` //玩家列表信息
}

func (x *QzcowcowOverResp) Reset() {
	*x = QzcowcowOverResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qzcowcow_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QzcowcowOverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QzcowcowOverResp) ProtoMessage() {}

func (x *QzcowcowOverResp) ProtoReflect() protoreflect.Message {
	mi := &file_qzcowcow_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QzcowcowOverResp.ProtoReflect.Descriptor instead.
func (*QzcowcowOverResp) Descriptor() ([]byte, []int) {
	return file_qzcowcow_proto_rawDescGZIP(), []int{18}
}

func (x *QzcowcowOverResp) GetAllPlayers() []*QzcowcowPlayer {
	if x != nil {
		return x.AllPlayers
	}
	return nil
}

var File_qzcowcow_proto protoreflect.FileDescriptor

var file_qzcowcow_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x71, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x67, 0x6f, 0x1a, 0x0e, 0x67, 0x61, 0x6d, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd4, 0x01, 0x0a, 0x0e, 0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f,
	0x77, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x06, 0x4d, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x4d, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x22, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x43, 0x61,
	0x72, 0x64, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x47, 0x61, 0x69, 0x6e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x47, 0x61, 0x69, 0x6e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x73, 0x0a, 0x11, 0x45,
	0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x51, 0x5a, 0x43, 0x43, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x69,
	0x72, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x43, 0x68, 0x61, 0x69,
	0x72, 0x4e, 0x75, 0x6d, 0x12, 0x2a, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x2e, 0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63,
	0x6f, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x22, 0xab, 0x01, 0x0a, 0x11, 0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x68, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x05, 0x43, 0x68, 0x69, 0x70, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x12, 0x32, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x2e, 0x51, 0x7a, 0x63, 0x6f,
	0x77, 0x63, 0x6f, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0a, 0x41, 0x6c, 0x6c, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x44,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x22, 0x53,
	0x0a, 0x15, 0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x74, 0x65, 0x46,
	0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x49,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x22, 0x3b, 0x0a, 0x15, 0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x22, 0x71, 0x0a, 0x17, 0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x44, 0x65, 0x63, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x65, 0x22, 0x3e, 0x0a, 0x18, 0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x22, 0x3b, 0x0a, 0x15, 0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x44, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x22, 0x6d, 0x0a, 0x15, 0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x30, 0x0a,
	0x08, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x6f, 0x2e, 0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x4f, 0x70, 0x65,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x3b, 0x0a, 0x15, 0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x4f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x4e, 0x0a, 0x10,
	0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x44, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x22, 0x2c, 0x0a, 0x10,
	0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x22, 0x45, 0x0a, 0x11, 0x51, 0x7a,
	0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x73, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64,
	0x79, 0x22, 0x2d, 0x0a, 0x0f, 0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x43, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65,
	0x22, 0x46, 0x0a, 0x10, 0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x43, 0x61, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x22, 0x46, 0x0a, 0x0e, 0x51, 0x7a, 0x63, 0x6f,
	0x77, 0x63, 0x6f, 0x77, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x65,
	0x74, 0x41, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x42, 0x65, 0x74,
	0x41, 0x72, 0x65, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x22, 0x5f, 0x0a, 0x0f, 0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x42, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x42,
	0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x42, 0x65,
	0x74, 0x41, 0x72, 0x65, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x22, 0x46, 0x0a, 0x10, 0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x4f, 0x70, 0x65,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x2e, 0x51,
	0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0a, 0x41,
	0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x46, 0x0a, 0x10, 0x51, 0x7a, 0x63,
	0x6f, 0x77, 0x63, 0x6f, 0x77, 0x4f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a,
	0x0a, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x2e, 0x51, 0x7a, 0x63, 0x6f, 0x77, 0x63, 0x6f, 0x77, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0a, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_qzcowcow_proto_rawDescOnce sync.Once
	file_qzcowcow_proto_rawDescData = file_qzcowcow_proto_rawDesc
)

func file_qzcowcow_proto_rawDescGZIP() []byte {
	file_qzcowcow_proto_rawDescOnce.Do(func() {
		file_qzcowcow_proto_rawDescData = protoimpl.X.CompressGZIP(file_qzcowcow_proto_rawDescData)
	})
	return file_qzcowcow_proto_rawDescData
}

var file_qzcowcow_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_qzcowcow_proto_goTypes = []interface{}{
	(*QzcowcowPlayer)(nil),           // 0: go.QzcowcowPlayer
	(*EnterGameQZCCResp)(nil),        // 1: go.EnterGameQZCCResp
	(*QzcowcowSceneResp)(nil),        // 2: go.QzcowcowSceneResp
	(*QzcowcowStateFreeResp)(nil),    // 3: go.QzcowcowStateFreeResp
	(*QzcowcowStateCallResp)(nil),    // 4: go.QzcowcowStateCallResp
	(*QzcowcowStateDecideResp)(nil),  // 5: go.QzcowcowStateDecideResp
	(*QzcowcowStatePlayingResp)(nil), // 6: go.QzcowcowStatePlayingResp
	(*QzcowcowStateDealResp)(nil),    // 7: go.QzcowcowStateDealResp
	(*QzcowcowStateOpenResp)(nil),    // 8: go.QzcowcowStateOpenResp
	(*QzcowcowStateOverResp)(nil),    // 9: go.QzcowcowStateOverResp
	(*QzcowcowDealResp)(nil),         // 10: go.QzcowcowDealResp
	(*QzcowcowReadyReq)(nil),         // 11: go.QzcowcowReadyReq
	(*QzcowcowReadyResp)(nil),        // 12: go.QzcowcowReadyResp
	(*QzcowcowCallReq)(nil),          // 13: go.QzcowcowCallReq
	(*QzcowcowCallResp)(nil),         // 14: go.QzcowcowCallResp
	(*QzcowcowBetReq)(nil),           // 15: go.QzcowcowBetReq
	(*QzcowcowBetResp)(nil),          // 16: go.QzcowcowBetResp
	(*QzcowcowOpenResp)(nil),         // 17: go.QzcowcowOpenResp
	(*QzcowcowOverResp)(nil),         // 18: go.QzcowcowOverResp
	(*PlayerInfo)(nil),               // 19: go.PlayerInfo
	(*CardInfo)(nil),                 // 20: go.CardInfo
	(*TimeInfo)(nil),                 // 21: go.TimeInfo
}
var file_qzcowcow_proto_depIdxs = []int32{
	19, // 0: go.QzcowcowPlayer.MyInfo:type_name -> go.PlayerInfo
	20, // 1: go.QzcowcowPlayer.Cards:type_name -> go.CardInfo
	0,  // 2: go.EnterGameQZCCResp.Player:type_name -> go.QzcowcowPlayer
	0,  // 3: go.QzcowcowSceneResp.AllPlayers:type_name -> go.QzcowcowPlayer
	21, // 4: go.QzcowcowStateFreeResp.Times:type_name -> go.TimeInfo
	21, // 5: go.QzcowcowStateCallResp.Times:type_name -> go.TimeInfo
	21, // 6: go.QzcowcowStateDecideResp.Times:type_name -> go.TimeInfo
	21, // 7: go.QzcowcowStatePlayingResp.Times:type_name -> go.TimeInfo
	21, // 8: go.QzcowcowStateDealResp.Times:type_name -> go.TimeInfo
	21, // 9: go.QzcowcowStateOpenResp.Times:type_name -> go.TimeInfo
	17, // 10: go.QzcowcowStateOpenResp.OpenInfo:type_name -> go.QzcowcowOpenResp
	21, // 11: go.QzcowcowStateOverResp.Times:type_name -> go.TimeInfo
	20, // 12: go.QzcowcowDealResp.Cards:type_name -> go.CardInfo
	0,  // 13: go.QzcowcowOpenResp.AllPlayers:type_name -> go.QzcowcowPlayer
	0,  // 14: go.QzcowcowOverResp.AllPlayers:type_name -> go.QzcowcowPlayer
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_qzcowcow_proto_init() }
func file_qzcowcow_proto_init() {
	if File_qzcowcow_proto != nil {
		return
	}
	file_gamecomm_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_qzcowcow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterGameQZCCResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowSceneResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowStateFreeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowStateCallResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowStateDecideResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowStatePlayingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowStateDealResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowStateOpenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowStateOverResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowDealResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowReadyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowReadyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowCallReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowCallResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowBetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowBetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowOpenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qzcowcow_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QzcowcowOverResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qzcowcow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qzcowcow_proto_goTypes,
		DependencyIndexes: file_qzcowcow_proto_depIdxs,
		MessageInfos:      file_qzcowcow_proto_msgTypes,
	}.Build()
	File_qzcowcow_proto = out.File
	file_qzcowcow_proto_rawDesc = nil
	file_qzcowcow_proto_goTypes = nil
	file_qzcowcow_proto_depIdxs = nil
}
