// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: tuitongzi.proto

package _go

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// kindID 3005
//    牌型    倍数
//    (0~6点)  1
//    (7~9点)  2
//    三公     3
//    炸弹     4
//    爆玖     5
//三公玩家信息
type TuitongziPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyInfo     *PlayerInfo `protobuf:"bytes,1,opt,name=MyInfo,proto3" json:"MyInfo,omitempty"`
	Cards      *CardInfo   `protobuf:"bytes,2,opt,name=Cards,proto3" json:"Cards,omitempty"`            //
	CallScore  int64       `protobuf:"varint,3,opt,name=CallScore,proto3" json:"CallScore,omitempty"`   //叫分分值
	BetScore   int64       `protobuf:"varint,4,opt,name=BetScore,proto3" json:"BetScore,omitempty"`     //下注分值
	GainScore  int64       `protobuf:"varint,5,opt,name=GainScore,proto3" json:"GainScore,omitempty"`   //输赢分值
	TotalScore int64       `protobuf:"varint,6,opt,name=TotalScore,proto3" json:"TotalScore,omitempty"` //总积分
}

func (x *TuitongziPlayer) Reset() {
	*x = TuitongziPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuitongzi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuitongziPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuitongziPlayer) ProtoMessage() {}

func (x *TuitongziPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_tuitongzi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuitongziPlayer.ProtoReflect.Descriptor instead.
func (*TuitongziPlayer) Descriptor() ([]byte, []int) {
	return file_tuitongzi_proto_rawDescGZIP(), []int{0}
}

func (x *TuitongziPlayer) GetMyInfo() *PlayerInfo {
	if x != nil {
		return x.MyInfo
	}
	return nil
}

func (x *TuitongziPlayer) GetCards() *CardInfo {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *TuitongziPlayer) GetCallScore() int64 {
	if x != nil {
		return x.CallScore
	}
	return 0
}

func (x *TuitongziPlayer) GetBetScore() int64 {
	if x != nil {
		return x.BetScore
	}
	return 0
}

func (x *TuitongziPlayer) GetGainScore() int64 {
	if x != nil {
		return x.GainScore
	}
	return 0
}

func (x *TuitongziPlayer) GetTotalScore() int64 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

//入场
type EnterGameTTZResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameID   uint64           `protobuf:"varint,1,opt,name=GameID,proto3" json:"GameID,omitempty"`     //游戏标识
	ChairNum uint32           `protobuf:"varint,2,opt,name=ChairNum,proto3" json:"ChairNum,omitempty"` //椅子编号(不满足req的此项时,将由系统分配,并返回提示)
	Player   *TuitongziPlayer `protobuf:"bytes,3,opt,name=Player,proto3" json:"Player,omitempty"`
}

func (x *EnterGameTTZResp) Reset() {
	*x = EnterGameTTZResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuitongzi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterGameTTZResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGameTTZResp) ProtoMessage() {}

func (x *EnterGameTTZResp) ProtoReflect() protoreflect.Message {
	mi := &file_tuitongzi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGameTTZResp.ProtoReflect.Descriptor instead.
func (*EnterGameTTZResp) Descriptor() ([]byte, []int) {
	return file_tuitongzi_proto_rawDescGZIP(), []int{1}
}

func (x *EnterGameTTZResp) GetGameID() uint64 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *EnterGameTTZResp) GetChairNum() uint32 {
	if x != nil {
		return x.ChairNum
	}
	return 0
}

func (x *EnterGameTTZResp) GetPlayer() *TuitongziPlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

//场景
type TuitongziSceneResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp  int64              `protobuf:"varint,1,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`  //时间戳
	Chips      []int32            `protobuf:"varint,2,rep,packed,name=Chips,proto3" json:"Chips,omitempty"`   //筹码
	Inning     string             `protobuf:"bytes,3,opt,name=Inning,proto3" json:"Inning,omitempty"`         // 牌局号
	AllPlayers []*TuitongziPlayer `protobuf:"bytes,4,rep,name=AllPlayers,proto3" json:"AllPlayers,omitempty"` //玩家列表信息
	HostID     uint64             `protobuf:"varint,5,opt,name=HostID,proto3" json:"HostID,omitempty"`        //庄家ID =0表示无人坐庄,牌值最大者获胜
}

func (x *TuitongziSceneResp) Reset() {
	*x = TuitongziSceneResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuitongzi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuitongziSceneResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuitongziSceneResp) ProtoMessage() {}

func (x *TuitongziSceneResp) ProtoReflect() protoreflect.Message {
	mi := &file_tuitongzi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuitongziSceneResp.ProtoReflect.Descriptor instead.
func (*TuitongziSceneResp) Descriptor() ([]byte, []int) {
	return file_tuitongzi_proto_rawDescGZIP(), []int{2}
}

func (x *TuitongziSceneResp) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *TuitongziSceneResp) GetChips() []int32 {
	if x != nil {
		return x.Chips
	}
	return nil
}

func (x *TuitongziSceneResp) GetInning() string {
	if x != nil {
		return x.Inning
	}
	return ""
}

func (x *TuitongziSceneResp) GetAllPlayers() []*TuitongziPlayer {
	if x != nil {
		return x.AllPlayers
	}
	return nil
}

func (x *TuitongziSceneResp) GetHostID() uint64 {
	if x != nil {
		return x.HostID
	}
	return 0
}

//状态
// 服务端推送
//(空闲 - )
type TuitongziStateFreeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times  *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
	Inning string    `protobuf:"bytes,2,opt,name=Inning,proto3" json:"Inning,omitempty"` // 牌局号
}

func (x *TuitongziStateFreeResp) Reset() {
	*x = TuitongziStateFreeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuitongzi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuitongziStateFreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuitongziStateFreeResp) ProtoMessage() {}

func (x *TuitongziStateFreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_tuitongzi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuitongziStateFreeResp.ProtoReflect.Descriptor instead.
func (*TuitongziStateFreeResp) Descriptor() ([]byte, []int) {
	return file_tuitongzi_proto_rawDescGZIP(), []int{3}
}

func (x *TuitongziStateFreeResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *TuitongziStateFreeResp) GetInning() string {
	if x != nil {
		return x.Inning
	}
	return ""
}

//(游戏中 - 下注)
type TuitongziStatePlayingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
}

func (x *TuitongziStatePlayingResp) Reset() {
	*x = TuitongziStatePlayingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuitongzi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuitongziStatePlayingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuitongziStatePlayingResp) ProtoMessage() {}

func (x *TuitongziStatePlayingResp) ProtoReflect() protoreflect.Message {
	mi := &file_tuitongzi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuitongziStatePlayingResp.ProtoReflect.Descriptor instead.
func (*TuitongziStatePlayingResp) Descriptor() ([]byte, []int) {
	return file_tuitongzi_proto_rawDescGZIP(), []int{4}
}

func (x *TuitongziStatePlayingResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

//(发牌)
type TuitongziStateDealResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
}

func (x *TuitongziStateDealResp) Reset() {
	*x = TuitongziStateDealResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuitongzi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuitongziStateDealResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuitongziStateDealResp) ProtoMessage() {}

func (x *TuitongziStateDealResp) ProtoReflect() protoreflect.Message {
	mi := &file_tuitongzi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuitongziStateDealResp.ProtoReflect.Descriptor instead.
func (*TuitongziStateDealResp) Descriptor() ([]byte, []int) {
	return file_tuitongzi_proto_rawDescGZIP(), []int{5}
}

func (x *TuitongziStateDealResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

//(摊牌)
type TuitongziStateOpenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times *TimeInfo `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
}

func (x *TuitongziStateOpenResp) Reset() {
	*x = TuitongziStateOpenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuitongzi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuitongziStateOpenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuitongziStateOpenResp) ProtoMessage() {}

func (x *TuitongziStateOpenResp) ProtoReflect() protoreflect.Message {
	mi := &file_tuitongzi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuitongziStateOpenResp.ProtoReflect.Descriptor instead.
func (*TuitongziStateOpenResp) Descriptor() ([]byte, []int) {
	return file_tuitongzi_proto_rawDescGZIP(), []int{6}
}

func (x *TuitongziStateOpenResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

//(结束)
type TuitongziStateOverResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times    *TimeInfo          `protobuf:"bytes,1,opt,name=Times,proto3" json:"Times,omitempty"`
	OpenInfo *TuitongziOverResp `protobuf:"bytes,2,opt,name=OpenInfo,proto3" json:"OpenInfo,omitempty"`
}

func (x *TuitongziStateOverResp) Reset() {
	*x = TuitongziStateOverResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuitongzi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuitongziStateOverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuitongziStateOverResp) ProtoMessage() {}

func (x *TuitongziStateOverResp) ProtoReflect() protoreflect.Message {
	mi := &file_tuitongzi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuitongziStateOverResp.ProtoReflect.Descriptor instead.
func (*TuitongziStateOverResp) Descriptor() ([]byte, []int) {
	return file_tuitongzi_proto_rawDescGZIP(), []int{7}
}

func (x *TuitongziStateOverResp) GetTimes() *TimeInfo {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *TuitongziStateOverResp) GetOpenInfo() *TuitongziOverResp {
	if x != nil {
		return x.OpenInfo
	}
	return nil
}

//////////有些玩家不配有牌////////
type TuitongziDealResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Cards  *CardInfo `protobuf:"bytes,2,opt,name=Cards,proto3" json:"Cards,omitempty"` //只有开奖时有真实值
}

func (x *TuitongziDealResp) Reset() {
	*x = TuitongziDealResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuitongzi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuitongziDealResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuitongziDealResp) ProtoMessage() {}

func (x *TuitongziDealResp) ProtoReflect() protoreflect.Message {
	mi := &file_tuitongzi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuitongziDealResp.ProtoReflect.Descriptor instead.
func (*TuitongziDealResp) Descriptor() ([]byte, []int) {
	return file_tuitongzi_proto_rawDescGZIP(), []int{8}
}

func (x *TuitongziDealResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *TuitongziDealResp) GetCards() *CardInfo {
	if x != nil {
		return x.Cards
	}
	return nil
}

//////////////////////////////////////
//准备
type TuitongziReadyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsReady bool `protobuf:"varint,1,opt,name=IsReady,proto3" json:"IsReady,omitempty"` // 玩家准备，可以取消准备
}

func (x *TuitongziReadyReq) Reset() {
	*x = TuitongziReadyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuitongzi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuitongziReadyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuitongziReadyReq) ProtoMessage() {}

func (x *TuitongziReadyReq) ProtoReflect() protoreflect.Message {
	mi := &file_tuitongzi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuitongziReadyReq.ProtoReflect.Descriptor instead.
func (*TuitongziReadyReq) Descriptor() ([]byte, []int) {
	return file_tuitongzi_proto_rawDescGZIP(), []int{9}
}

func (x *TuitongziReadyReq) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type TuitongziReadyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID  uint64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	IsReady bool   `protobuf:"varint,2,opt,name=IsReady,proto3" json:"IsReady,omitempty"` // 玩家准备，可以取消准备
}

func (x *TuitongziReadyResp) Reset() {
	*x = TuitongziReadyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuitongzi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuitongziReadyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuitongziReadyResp) ProtoMessage() {}

func (x *TuitongziReadyResp) ProtoReflect() protoreflect.Message {
	mi := &file_tuitongzi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuitongziReadyResp.ProtoReflect.Descriptor instead.
func (*TuitongziReadyResp) Descriptor() ([]byte, []int) {
	return file_tuitongzi_proto_rawDescGZIP(), []int{10}
}

func (x *TuitongziReadyResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *TuitongziReadyResp) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

//下注
type TuitongziBetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BetScore int64 `protobuf:"varint,1,opt,name=BetScore,proto3" json:"BetScore,omitempty"` //倍数
}

func (x *TuitongziBetReq) Reset() {
	*x = TuitongziBetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuitongzi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuitongziBetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuitongziBetReq) ProtoMessage() {}

func (x *TuitongziBetReq) ProtoReflect() protoreflect.Message {
	mi := &file_tuitongzi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuitongziBetReq.ProtoReflect.Descriptor instead.
func (*TuitongziBetReq) Descriptor() ([]byte, []int) {
	return file_tuitongzi_proto_rawDescGZIP(), []int{11}
}

func (x *TuitongziBetReq) GetBetScore() int64 {
	if x != nil {
		return x.BetScore
	}
	return 0
}

type TuitongziBetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   uint64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BetScore int64  `protobuf:"varint,2,opt,name=BetScore,proto3" json:"BetScore,omitempty"` //倍数
}

func (x *TuitongziBetResp) Reset() {
	*x = TuitongziBetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuitongzi_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuitongziBetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuitongziBetResp) ProtoMessage() {}

func (x *TuitongziBetResp) ProtoReflect() protoreflect.Message {
	mi := &file_tuitongzi_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuitongziBetResp.ProtoReflect.Descriptor instead.
func (*TuitongziBetResp) Descriptor() ([]byte, []int) {
	return file_tuitongzi_proto_rawDescGZIP(), []int{12}
}

func (x *TuitongziBetResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *TuitongziBetResp) GetBetScore() int64 {
	if x != nil {
		return x.BetScore
	}
	return 0
}

//摊牌
type TuitongziOutCardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TuitongziOutCardReq) Reset() {
	*x = TuitongziOutCardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuitongzi_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuitongziOutCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuitongziOutCardReq) ProtoMessage() {}

func (x *TuitongziOutCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_tuitongzi_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuitongziOutCardReq.ProtoReflect.Descriptor instead.
func (*TuitongziOutCardReq) Descriptor() ([]byte, []int) {
	return file_tuitongzi_proto_rawDescGZIP(), []int{13}
}

type TuitongziOutCardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Cards  *CardInfo `protobuf:"bytes,2,opt,name=Cards,proto3" json:"Cards,omitempty"` //
}

func (x *TuitongziOutCardResp) Reset() {
	*x = TuitongziOutCardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuitongzi_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuitongziOutCardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuitongziOutCardResp) ProtoMessage() {}

func (x *TuitongziOutCardResp) ProtoReflect() protoreflect.Message {
	mi := &file_tuitongzi_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuitongziOutCardResp.ProtoReflect.Descriptor instead.
func (*TuitongziOutCardResp) Descriptor() ([]byte, []int) {
	return file_tuitongzi_proto_rawDescGZIP(), []int{14}
}

func (x *TuitongziOutCardResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *TuitongziOutCardResp) GetCards() *CardInfo {
	if x != nil {
		return x.Cards
	}
	return nil
}

//结算
type TuitongziOverResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllPlayers []*TuitongziPlayer `protobuf:"bytes,1,rep,name=AllPlayers,proto3" json:"AllPlayers,omitempty"` //玩家列表信息
}

func (x *TuitongziOverResp) Reset() {
	*x = TuitongziOverResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuitongzi_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuitongziOverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuitongziOverResp) ProtoMessage() {}

func (x *TuitongziOverResp) ProtoReflect() protoreflect.Message {
	mi := &file_tuitongzi_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuitongziOverResp.ProtoReflect.Descriptor instead.
func (*TuitongziOverResp) Descriptor() ([]byte, []int) {
	return file_tuitongzi_proto_rawDescGZIP(), []int{15}
}

func (x *TuitongziOverResp) GetAllPlayers() []*TuitongziPlayer {
	if x != nil {
		return x.AllPlayers
	}
	return nil
}

var File_tuitongzi_proto protoreflect.FileDescriptor

var file_tuitongzi_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x67, 0x6f, 0x1a, 0x0e, 0x67, 0x61, 0x6d, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd5, 0x01, 0x0a, 0x0f, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e,
	0x67, 0x7a, 0x69, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x06, 0x4d, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x4d, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x22, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x47, 0x61, 0x69, 0x6e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x47, 0x61, 0x69, 0x6e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x73, 0x0a,
	0x10, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x54, 0x5a, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x68, 0x61,
	0x69, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x43, 0x68, 0x61,
	0x69, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x2b, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x75, 0x69, 0x74, 0x6f,
	0x6e, 0x67, 0x7a, 0x69, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x22, 0xad, 0x01, 0x0a, 0x12, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x68, 0x69, 0x70, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x43, 0x68, 0x69, 0x70, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x49, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x33, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x6f, 0x2e, 0x54,
	0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0a,
	0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x6f,
	0x73, 0x74, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x48, 0x6f, 0x73, 0x74,
	0x49, 0x44, 0x22, 0x54, 0x0a, 0x16, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x46, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x49, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x49, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x3f, 0x0a, 0x19, 0x54, 0x75, 0x69, 0x74,
	0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x16, 0x54, 0x75, 0x69,
	0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44, 0x65, 0x61, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x16, 0x54, 0x75, 0x69, 0x74, 0x6f,
	0x6e, 0x67, 0x7a, 0x69, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x6f, 0x0a, 0x16, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67,
	0x7a, 0x69, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x22, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x6f, 0x2e, 0x54, 0x75, 0x69, 0x74, 0x6f,
	0x6e, 0x67, 0x7a, 0x69, 0x4f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x4f, 0x70,
	0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x4f, 0x0a, 0x11, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e,
	0x67, 0x7a, 0x69, 0x44, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x22, 0x2d, 0x0a, 0x11, 0x54, 0x75, 0x69, 0x74, 0x6f,
	0x6e, 0x67, 0x7a, 0x69, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x49,
	0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x22, 0x46, 0x0a, 0x12, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e,
	0x67, 0x7a, 0x69, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x22, 0x2d,
	0x0a, 0x0f, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x42, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x46, 0x0a,
	0x10, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x42, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x65, 0x74,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x65, 0x74,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67,
	0x7a, 0x69, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x22, 0x52, 0x0a, 0x14,
	0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x05,
	0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f,
	0x2e, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73,
	0x22, 0x48, 0x0a, 0x11, 0x54, 0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x4f, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x6f, 0x2e, 0x54,
	0x75, 0x69, 0x74, 0x6f, 0x6e, 0x67, 0x7a, 0x69, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0a,
	0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_tuitongzi_proto_rawDescOnce sync.Once
	file_tuitongzi_proto_rawDescData = file_tuitongzi_proto_rawDesc
)

func file_tuitongzi_proto_rawDescGZIP() []byte {
	file_tuitongzi_proto_rawDescOnce.Do(func() {
		file_tuitongzi_proto_rawDescData = protoimpl.X.CompressGZIP(file_tuitongzi_proto_rawDescData)
	})
	return file_tuitongzi_proto_rawDescData
}

var file_tuitongzi_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_tuitongzi_proto_goTypes = []interface{}{
	(*TuitongziPlayer)(nil),           // 0: go.TuitongziPlayer
	(*EnterGameTTZResp)(nil),          // 1: go.EnterGameTTZResp
	(*TuitongziSceneResp)(nil),        // 2: go.TuitongziSceneResp
	(*TuitongziStateFreeResp)(nil),    // 3: go.TuitongziStateFreeResp
	(*TuitongziStatePlayingResp)(nil), // 4: go.TuitongziStatePlayingResp
	(*TuitongziStateDealResp)(nil),    // 5: go.TuitongziStateDealResp
	(*TuitongziStateOpenResp)(nil),    // 6: go.TuitongziStateOpenResp
	(*TuitongziStateOverResp)(nil),    // 7: go.TuitongziStateOverResp
	(*TuitongziDealResp)(nil),         // 8: go.TuitongziDealResp
	(*TuitongziReadyReq)(nil),         // 9: go.TuitongziReadyReq
	(*TuitongziReadyResp)(nil),        // 10: go.TuitongziReadyResp
	(*TuitongziBetReq)(nil),           // 11: go.TuitongziBetReq
	(*TuitongziBetResp)(nil),          // 12: go.TuitongziBetResp
	(*TuitongziOutCardReq)(nil),       // 13: go.TuitongziOutCardReq
	(*TuitongziOutCardResp)(nil),      // 14: go.TuitongziOutCardResp
	(*TuitongziOverResp)(nil),         // 15: go.TuitongziOverResp
	(*PlayerInfo)(nil),                // 16: go.PlayerInfo
	(*CardInfo)(nil),                  // 17: go.CardInfo
	(*TimeInfo)(nil),                  // 18: go.TimeInfo
}
var file_tuitongzi_proto_depIdxs = []int32{
	16, // 0: go.TuitongziPlayer.MyInfo:type_name -> go.PlayerInfo
	17, // 1: go.TuitongziPlayer.Cards:type_name -> go.CardInfo
	0,  // 2: go.EnterGameTTZResp.Player:type_name -> go.TuitongziPlayer
	0,  // 3: go.TuitongziSceneResp.AllPlayers:type_name -> go.TuitongziPlayer
	18, // 4: go.TuitongziStateFreeResp.Times:type_name -> go.TimeInfo
	18, // 5: go.TuitongziStatePlayingResp.Times:type_name -> go.TimeInfo
	18, // 6: go.TuitongziStateDealResp.Times:type_name -> go.TimeInfo
	18, // 7: go.TuitongziStateOpenResp.Times:type_name -> go.TimeInfo
	18, // 8: go.TuitongziStateOverResp.Times:type_name -> go.TimeInfo
	15, // 9: go.TuitongziStateOverResp.OpenInfo:type_name -> go.TuitongziOverResp
	17, // 10: go.TuitongziDealResp.Cards:type_name -> go.CardInfo
	17, // 11: go.TuitongziOutCardResp.Cards:type_name -> go.CardInfo
	0,  // 12: go.TuitongziOverResp.AllPlayers:type_name -> go.TuitongziPlayer
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_tuitongzi_proto_init() }
func file_tuitongzi_proto_init() {
	if File_tuitongzi_proto != nil {
		return
	}
	file_gamecomm_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tuitongzi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TuitongziPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuitongzi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterGameTTZResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuitongzi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TuitongziSceneResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuitongzi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TuitongziStateFreeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuitongzi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TuitongziStatePlayingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuitongzi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TuitongziStateDealResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuitongzi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TuitongziStateOpenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuitongzi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TuitongziStateOverResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuitongzi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TuitongziDealResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuitongzi_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TuitongziReadyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuitongzi_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TuitongziReadyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuitongzi_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TuitongziBetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuitongzi_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TuitongziBetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuitongzi_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TuitongziOutCardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuitongzi_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TuitongziOutCardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuitongzi_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TuitongziOverResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tuitongzi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tuitongzi_proto_goTypes,
		DependencyIndexes: file_tuitongzi_proto_depIdxs,
		MessageInfos:      file_tuitongzi_proto_msgTypes,
	}.Build()
	File_tuitongzi_proto = out.File
	file_tuitongzi_proto_rawDesc = nil
	file_tuitongzi_proto_goTypes = nil
	file_tuitongzi_proto_depIdxs = nil
}
