// Code generated by protoc-gen-go. DO NOT EDIT.
// source: baccarat.proto

package _go

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//场景
//入场
type GameBaccaratEnter struct {
	UserInfo             *PlayerInfo `protobuf:"bytes,1,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
	TimeStamp            int64       `protobuf:"varint,2,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Chips                []int32     `protobuf:"varint,3,rep,packed,name=Chips,proto3" json:"Chips,omitempty"`
	AwardAreas           [][]byte    `protobuf:"bytes,4,rep,name=AwardAreas,proto3" json:"AwardAreas,omitempty"`
	FreeTime             uint32      `protobuf:"varint,5,opt,name=FreeTime,proto3" json:"FreeTime,omitempty"`
	BetTime              uint32      `protobuf:"varint,6,opt,name=BetTime,proto3" json:"BetTime,omitempty"`
	OpenTime             uint32      `protobuf:"varint,7,opt,name=OpenTime,proto3" json:"OpenTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GameBaccaratEnter) Reset()         { *m = GameBaccaratEnter{} }
func (m *GameBaccaratEnter) String() string { return proto.CompactTextString(m) }
func (*GameBaccaratEnter) ProtoMessage()    {}
func (*GameBaccaratEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bef2faf2a7bc098, []int{0}
}

func (m *GameBaccaratEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBaccaratEnter.Unmarshal(m, b)
}
func (m *GameBaccaratEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBaccaratEnter.Marshal(b, m, deterministic)
}
func (m *GameBaccaratEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBaccaratEnter.Merge(m, src)
}
func (m *GameBaccaratEnter) XXX_Size() int {
	return xxx_messageInfo_GameBaccaratEnter.Size(m)
}
func (m *GameBaccaratEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBaccaratEnter.DiscardUnknown(m)
}

var xxx_messageInfo_GameBaccaratEnter proto.InternalMessageInfo

func (m *GameBaccaratEnter) GetUserInfo() *PlayerInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *GameBaccaratEnter) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *GameBaccaratEnter) GetChips() []int32 {
	if m != nil {
		return m.Chips
	}
	return nil
}

func (m *GameBaccaratEnter) GetAwardAreas() [][]byte {
	if m != nil {
		return m.AwardAreas
	}
	return nil
}

func (m *GameBaccaratEnter) GetFreeTime() uint32 {
	if m != nil {
		return m.FreeTime
	}
	return 0
}

func (m *GameBaccaratEnter) GetBetTime() uint32 {
	if m != nil {
		return m.BetTime
	}
	return 0
}

func (m *GameBaccaratEnter) GetOpenTime() uint32 {
	if m != nil {
		return m.OpenTime
	}
	return 0
}

//游戏消息
//抢庄
type GameBaccaratHost struct {
	UserID               uint64   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	IsWant               bool     `protobuf:"varint,2,opt,name=IsWant,proto3" json:"IsWant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameBaccaratHost) Reset()         { *m = GameBaccaratHost{} }
func (m *GameBaccaratHost) String() string { return proto.CompactTextString(m) }
func (*GameBaccaratHost) ProtoMessage()    {}
func (*GameBaccaratHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bef2faf2a7bc098, []int{1}
}

func (m *GameBaccaratHost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBaccaratHost.Unmarshal(m, b)
}
func (m *GameBaccaratHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBaccaratHost.Marshal(b, m, deterministic)
}
func (m *GameBaccaratHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBaccaratHost.Merge(m, src)
}
func (m *GameBaccaratHost) XXX_Size() int {
	return xxx_messageInfo_GameBaccaratHost.Size(m)
}
func (m *GameBaccaratHost) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBaccaratHost.DiscardUnknown(m)
}

var xxx_messageInfo_GameBaccaratHost proto.InternalMessageInfo

func (m *GameBaccaratHost) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GameBaccaratHost) GetIsWant() bool {
	if m != nil {
		return m.IsWant
	}
	return false
}

//超级抢庄
type GameBaccaratSuperHost struct {
	UserID               uint64   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	IsWant               bool     `protobuf:"varint,2,opt,name=IsWant,proto3" json:"IsWant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameBaccaratSuperHost) Reset()         { *m = GameBaccaratSuperHost{} }
func (m *GameBaccaratSuperHost) String() string { return proto.CompactTextString(m) }
func (*GameBaccaratSuperHost) ProtoMessage()    {}
func (*GameBaccaratSuperHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bef2faf2a7bc098, []int{2}
}

func (m *GameBaccaratSuperHost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBaccaratSuperHost.Unmarshal(m, b)
}
func (m *GameBaccaratSuperHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBaccaratSuperHost.Marshal(b, m, deterministic)
}
func (m *GameBaccaratSuperHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBaccaratSuperHost.Merge(m, src)
}
func (m *GameBaccaratSuperHost) XXX_Size() int {
	return xxx_messageInfo_GameBaccaratSuperHost.Size(m)
}
func (m *GameBaccaratSuperHost) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBaccaratSuperHost.DiscardUnknown(m)
}

var xxx_messageInfo_GameBaccaratSuperHost proto.InternalMessageInfo

func (m *GameBaccaratSuperHost) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GameBaccaratSuperHost) GetIsWant() bool {
	if m != nil {
		return m.IsWant
	}
	return false
}

//游戏中
type GameBaccaratBet struct {
	BetArea              int32    `protobuf:"varint,1,opt,name=BetArea,proto3" json:"BetArea,omitempty"`
	BetScore             int64    `protobuf:"varint,2,opt,name=BetScore,proto3" json:"BetScore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameBaccaratBet) Reset()         { *m = GameBaccaratBet{} }
func (m *GameBaccaratBet) String() string { return proto.CompactTextString(m) }
func (*GameBaccaratBet) ProtoMessage()    {}
func (*GameBaccaratBet) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bef2faf2a7bc098, []int{3}
}

func (m *GameBaccaratBet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBaccaratBet.Unmarshal(m, b)
}
func (m *GameBaccaratBet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBaccaratBet.Marshal(b, m, deterministic)
}
func (m *GameBaccaratBet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBaccaratBet.Merge(m, src)
}
func (m *GameBaccaratBet) XXX_Size() int {
	return xxx_messageInfo_GameBaccaratBet.Size(m)
}
func (m *GameBaccaratBet) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBaccaratBet.DiscardUnknown(m)
}

var xxx_messageInfo_GameBaccaratBet proto.InternalMessageInfo

func (m *GameBaccaratBet) GetBetArea() int32 {
	if m != nil {
		return m.BetArea
	}
	return 0
}

func (m *GameBaccaratBet) GetBetScore() int64 {
	if m != nil {
		return m.BetScore
	}
	return 0
}

//下注结果
type GameBaccaratBetResult struct {
	State                int32    `protobuf:"varint,1,opt,name=State,proto3" json:"State,omitempty"`
	Hints                string   `protobuf:"bytes,2,opt,name=Hints,proto3" json:"Hints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameBaccaratBetResult) Reset()         { *m = GameBaccaratBetResult{} }
func (m *GameBaccaratBetResult) String() string { return proto.CompactTextString(m) }
func (*GameBaccaratBetResult) ProtoMessage()    {}
func (*GameBaccaratBetResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bef2faf2a7bc098, []int{4}
}

func (m *GameBaccaratBetResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBaccaratBetResult.Unmarshal(m, b)
}
func (m *GameBaccaratBetResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBaccaratBetResult.Marshal(b, m, deterministic)
}
func (m *GameBaccaratBetResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBaccaratBetResult.Merge(m, src)
}
func (m *GameBaccaratBetResult) XXX_Size() int {
	return xxx_messageInfo_GameBaccaratBetResult.Size(m)
}
func (m *GameBaccaratBetResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBaccaratBetResult.DiscardUnknown(m)
}

var xxx_messageInfo_GameBaccaratBetResult proto.InternalMessageInfo

func (m *GameBaccaratBetResult) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *GameBaccaratBetResult) GetHints() string {
	if m != nil {
		return m.Hints
	}
	return ""
}

//结束
type GameBaccaratOver struct {
	AwardArea            []byte   `protobuf:"bytes,1,opt,name=AwardArea,proto3" json:"AwardArea,omitempty"`
	PlayerCard           []byte   `protobuf:"bytes,2,opt,name=PlayerCard,proto3" json:"PlayerCard,omitempty"`
	BankerCard           []byte   `protobuf:"bytes,3,opt,name=BankerCard,proto3" json:"BankerCard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameBaccaratOver) Reset()         { *m = GameBaccaratOver{} }
func (m *GameBaccaratOver) String() string { return proto.CompactTextString(m) }
func (*GameBaccaratOver) ProtoMessage()    {}
func (*GameBaccaratOver) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bef2faf2a7bc098, []int{5}
}

func (m *GameBaccaratOver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBaccaratOver.Unmarshal(m, b)
}
func (m *GameBaccaratOver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBaccaratOver.Marshal(b, m, deterministic)
}
func (m *GameBaccaratOver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBaccaratOver.Merge(m, src)
}
func (m *GameBaccaratOver) XXX_Size() int {
	return xxx_messageInfo_GameBaccaratOver.Size(m)
}
func (m *GameBaccaratOver) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBaccaratOver.DiscardUnknown(m)
}

var xxx_messageInfo_GameBaccaratOver proto.InternalMessageInfo

func (m *GameBaccaratOver) GetAwardArea() []byte {
	if m != nil {
		return m.AwardArea
	}
	return nil
}

func (m *GameBaccaratOver) GetPlayerCard() []byte {
	if m != nil {
		return m.PlayerCard
	}
	return nil
}

func (m *GameBaccaratOver) GetBankerCard() []byte {
	if m != nil {
		return m.BankerCard
	}
	return nil
}

//结算
type GameBaccaratCheckout struct {
	Acquire              int64    `protobuf:"varint,1,opt,name=Acquire,proto3" json:"Acquire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameBaccaratCheckout) Reset()         { *m = GameBaccaratCheckout{} }
func (m *GameBaccaratCheckout) String() string { return proto.CompactTextString(m) }
func (*GameBaccaratCheckout) ProtoMessage()    {}
func (*GameBaccaratCheckout) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bef2faf2a7bc098, []int{6}
}

func (m *GameBaccaratCheckout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBaccaratCheckout.Unmarshal(m, b)
}
func (m *GameBaccaratCheckout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBaccaratCheckout.Marshal(b, m, deterministic)
}
func (m *GameBaccaratCheckout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBaccaratCheckout.Merge(m, src)
}
func (m *GameBaccaratCheckout) XXX_Size() int {
	return xxx_messageInfo_GameBaccaratCheckout.Size(m)
}
func (m *GameBaccaratCheckout) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBaccaratCheckout.DiscardUnknown(m)
}

var xxx_messageInfo_GameBaccaratCheckout proto.InternalMessageInfo

func (m *GameBaccaratCheckout) GetAcquire() int64 {
	if m != nil {
		return m.Acquire
	}
	return 0
}

func init() {
	proto.RegisterType((*GameBaccaratEnter)(nil), "go.GameBaccaratEnter")
	proto.RegisterType((*GameBaccaratHost)(nil), "go.GameBaccaratHost")
	proto.RegisterType((*GameBaccaratSuperHost)(nil), "go.GameBaccaratSuperHost")
	proto.RegisterType((*GameBaccaratBet)(nil), "go.GameBaccaratBet")
	proto.RegisterType((*GameBaccaratBetResult)(nil), "go.GameBaccaratBetResult")
	proto.RegisterType((*GameBaccaratOver)(nil), "go.GameBaccaratOver")
	proto.RegisterType((*GameBaccaratCheckout)(nil), "go.GameBaccaratCheckout")
}

func init() { proto.RegisterFile("baccarat.proto", fileDescriptor_4bef2faf2a7bc098) }

var fileDescriptor_4bef2faf2a7bc098 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xdf, 0x4e, 0x83, 0x30,
	0x18, 0xc5, 0xc3, 0x18, 0xfb, 0x53, 0xe7, 0xd4, 0x66, 0x1a, 0xb2, 0x18, 0x43, 0xb8, 0x22, 0x5e,
	0x2c, 0x46, 0x9f, 0x60, 0xa0, 0x6e, 0xbb, 0x9a, 0x29, 0x1a, 0xaf, 0x3b, 0xf6, 0xb9, 0x91, 0x0d,
	0x8a, 0xa5, 0x68, 0x7c, 0x60, 0xdf, 0xc3, 0xb4, 0x05, 0xc6, 0x6e, 0xbd, 0xfc, 0x9d, 0x43, 0x0f,
	0x3d, 0xdf, 0x57, 0x34, 0x5c, 0xd1, 0x28, 0xa2, 0x9c, 0x8a, 0x49, 0xc6, 0x99, 0x60, 0xb8, 0xb5,
	0x61, 0xe3, 0xe1, 0x86, 0x26, 0x10, 0xb1, 0x24, 0xd1, 0x9a, 0xfb, 0x6b, 0xa0, 0x8b, 0x19, 0x4d,
	0xc0, 0x2f, 0x3f, 0x7d, 0x4a, 0x05, 0x70, 0x7c, 0x8b, 0x7a, 0x6f, 0x39, 0xf0, 0x45, 0xfa, 0xc1,
	0x6c, 0xc3, 0x31, 0xbc, 0x93, 0xfb, 0xe1, 0x64, 0xc3, 0x26, 0x2f, 0x7b, 0xfa, 0xa3, 0x55, 0x52,
	0xfb, 0xf8, 0x1a, 0xf5, 0x5f, 0xe3, 0x04, 0x42, 0x41, 0x93, 0xcc, 0x6e, 0x39, 0x86, 0x67, 0x92,
	0x83, 0x80, 0x47, 0xc8, 0x0a, 0xb6, 0x71, 0x96, 0xdb, 0xa6, 0x63, 0x7a, 0x16, 0xd1, 0x80, 0x6f,
	0x10, 0x9a, 0x7e, 0x53, 0xbe, 0x9e, 0x72, 0xa0, 0xb9, 0xdd, 0x76, 0x4c, 0x6f, 0x40, 0x1a, 0x0a,
	0x1e, 0xa3, 0xde, 0x33, 0x07, 0x90, 0x31, 0xb6, 0xe5, 0x18, 0xde, 0x29, 0xa9, 0x19, 0xdb, 0xa8,
	0xeb, 0x83, 0x50, 0x56, 0x47, 0x59, 0x15, 0xca, 0x53, 0xcb, 0x0c, 0x52, 0x65, 0x75, 0xf5, 0xa9,
	0x8a, 0x5d, 0x1f, 0x9d, 0x37, 0x6b, 0xce, 0x59, 0x2e, 0xf0, 0x15, 0xea, 0xa8, 0x16, 0x8f, 0xaa,
	0x63, 0x9b, 0x94, 0x24, 0xf5, 0x45, 0xfe, 0x4e, 0x53, 0xa1, 0xea, 0xf4, 0x48, 0x49, 0xee, 0x0c,
	0x5d, 0x36, 0x33, 0xc2, 0x22, 0x03, 0xfe, 0xcf, 0xa0, 0xb3, 0x66, 0x90, 0x0f, 0xa2, 0x6c, 0x25,
	0xdb, 0xab, 0x0c, 0x8b, 0x54, 0x28, 0x5b, 0xf9, 0x20, 0xc2, 0x88, 0x71, 0x28, 0xc7, 0x5b, 0xb3,
	0x1b, 0x1c, 0xdf, 0xc8, 0x07, 0x41, 0x20, 0x2f, 0xf6, 0x42, 0x8e, 0x3d, 0x14, 0x54, 0x40, 0x19,
	0xa6, 0x41, 0xaa, 0xf3, 0x38, 0x15, 0xb9, 0xca, 0xe9, 0x13, 0x0d, 0x6e, 0x76, 0x3c, 0x9a, 0xe5,
	0x17, 0x70, 0xb9, 0xd4, 0x7a, 0x1d, 0x2a, 0x63, 0x40, 0x0e, 0x82, 0x5c, 0x9f, 0x7e, 0x0a, 0x01,
	0xe5, 0x6b, 0x15, 0x36, 0x20, 0x0d, 0x45, 0xfa, 0x3e, 0x4d, 0x77, 0xa5, 0x6f, 0x6a, 0xff, 0xa0,
	0xb8, 0x77, 0x68, 0xd4, 0xfc, 0x63, 0xb0, 0x85, 0x68, 0xc7, 0x0a, 0x35, 0x84, 0x69, 0xf4, 0x59,
	0xc4, 0x5c, 0xdf, 0xdb, 0x24, 0x15, 0xae, 0x3a, 0xea, 0xb5, 0x3e, 0xfc, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x65, 0xd4, 0x3f, 0x20, 0xd3, 0x02, 0x00, 0x00,
}
