// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cowcow.proto

package _go

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//【百人类游戏】
//入场 (场景)
type GameCowcowEnter struct {
	AwardAreas           []int32  `protobuf:"varint,1,rep,packed,name=AwardAreas,proto3" json:"AwardAreas,omitempty"`
	Players              []string `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Countdown            int32    `protobuf:"varint,3,opt,name=Countdown,proto3" json:"Countdown,omitempty"`
	Chips                []int32  `protobuf:"varint,4,rep,packed,name=Chips,proto3" json:"Chips,omitempty"`
	Odds                 []int32  `protobuf:"varint,5,rep,packed,name=Odds,proto3" json:"Odds,omitempty"`
	BankerScore          float32  `protobuf:"fixed32,6,opt,name=BankerScore,proto3" json:"BankerScore,omitempty"`
	PlayerScore          float32  `protobuf:"fixed32,7,opt,name=PlayerScore,proto3" json:"PlayerScore,omitempty"`
	Acquire              float32  `protobuf:"fixed32,8,opt,name=Acquire,proto3" json:"Acquire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameCowcowEnter) Reset()         { *m = GameCowcowEnter{} }
func (m *GameCowcowEnter) String() string { return proto.CompactTextString(m) }
func (*GameCowcowEnter) ProtoMessage()    {}
func (*GameCowcowEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_626b438dd4edf163, []int{0}
}

func (m *GameCowcowEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameCowcowEnter.Unmarshal(m, b)
}
func (m *GameCowcowEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameCowcowEnter.Marshal(b, m, deterministic)
}
func (m *GameCowcowEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameCowcowEnter.Merge(m, src)
}
func (m *GameCowcowEnter) XXX_Size() int {
	return xxx_messageInfo_GameCowcowEnter.Size(m)
}
func (m *GameCowcowEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_GameCowcowEnter.DiscardUnknown(m)
}

var xxx_messageInfo_GameCowcowEnter proto.InternalMessageInfo

func (m *GameCowcowEnter) GetAwardAreas() []int32 {
	if m != nil {
		return m.AwardAreas
	}
	return nil
}

func (m *GameCowcowEnter) GetPlayers() []string {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *GameCowcowEnter) GetCountdown() int32 {
	if m != nil {
		return m.Countdown
	}
	return 0
}

func (m *GameCowcowEnter) GetChips() []int32 {
	if m != nil {
		return m.Chips
	}
	return nil
}

func (m *GameCowcowEnter) GetOdds() []int32 {
	if m != nil {
		return m.Odds
	}
	return nil
}

func (m *GameCowcowEnter) GetBankerScore() float32 {
	if m != nil {
		return m.BankerScore
	}
	return 0
}

func (m *GameCowcowEnter) GetPlayerScore() float32 {
	if m != nil {
		return m.PlayerScore
	}
	return 0
}

func (m *GameCowcowEnter) GetAcquire() float32 {
	if m != nil {
		return m.Acquire
	}
	return 0
}

//游戏消息
//游戏中
type GameCowcowPlaying struct {
	BetArea              int32    `protobuf:"varint,1,opt,name=BetArea,proto3" json:"BetArea,omitempty"`
	BetScore             float32  `protobuf:"fixed32,2,opt,name=BetScore,proto3" json:"BetScore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameCowcowPlaying) Reset()         { *m = GameCowcowPlaying{} }
func (m *GameCowcowPlaying) String() string { return proto.CompactTextString(m) }
func (*GameCowcowPlaying) ProtoMessage()    {}
func (*GameCowcowPlaying) Descriptor() ([]byte, []int) {
	return fileDescriptor_626b438dd4edf163, []int{1}
}

func (m *GameCowcowPlaying) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameCowcowPlaying.Unmarshal(m, b)
}
func (m *GameCowcowPlaying) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameCowcowPlaying.Marshal(b, m, deterministic)
}
func (m *GameCowcowPlaying) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameCowcowPlaying.Merge(m, src)
}
func (m *GameCowcowPlaying) XXX_Size() int {
	return xxx_messageInfo_GameCowcowPlaying.Size(m)
}
func (m *GameCowcowPlaying) XXX_DiscardUnknown() {
	xxx_messageInfo_GameCowcowPlaying.DiscardUnknown(m)
}

var xxx_messageInfo_GameCowcowPlaying proto.InternalMessageInfo

func (m *GameCowcowPlaying) GetBetArea() int32 {
	if m != nil {
		return m.BetArea
	}
	return 0
}

func (m *GameCowcowPlaying) GetBetScore() float32 {
	if m != nil {
		return m.BetScore
	}
	return 0
}

//下注结果
type GameCowcowBetResult struct {
	State                int32    `protobuf:"varint,1,opt,name=State,proto3" json:"State,omitempty"`
	Hints                string   `protobuf:"bytes,2,opt,name=Hints,proto3" json:"Hints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameCowcowBetResult) Reset()         { *m = GameCowcowBetResult{} }
func (m *GameCowcowBetResult) String() string { return proto.CompactTextString(m) }
func (*GameCowcowBetResult) ProtoMessage()    {}
func (*GameCowcowBetResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_626b438dd4edf163, []int{2}
}

func (m *GameCowcowBetResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameCowcowBetResult.Unmarshal(m, b)
}
func (m *GameCowcowBetResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameCowcowBetResult.Marshal(b, m, deterministic)
}
func (m *GameCowcowBetResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameCowcowBetResult.Merge(m, src)
}
func (m *GameCowcowBetResult) XXX_Size() int {
	return xxx_messageInfo_GameCowcowBetResult.Size(m)
}
func (m *GameCowcowBetResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GameCowcowBetResult.DiscardUnknown(m)
}

var xxx_messageInfo_GameCowcowBetResult proto.InternalMessageInfo

func (m *GameCowcowBetResult) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *GameCowcowBetResult) GetHints() string {
	if m != nil {
		return m.Hints
	}
	return ""
}

//结束
type GameCowcowOver struct {
	AwardArea            []int32  `protobuf:"varint,1,rep,packed,name=AwardArea,proto3" json:"AwardArea,omitempty"`
	PlayerCard           []int32  `protobuf:"varint,2,rep,packed,name=PlayerCard,proto3" json:"PlayerCard,omitempty"`
	BankerCard           []int32  `protobuf:"varint,3,rep,packed,name=BankerCard,proto3" json:"BankerCard,omitempty"`
	Acquire              float32  `protobuf:"fixed32,4,opt,name=Acquire,proto3" json:"Acquire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameCowcowOver) Reset()         { *m = GameCowcowOver{} }
func (m *GameCowcowOver) String() string { return proto.CompactTextString(m) }
func (*GameCowcowOver) ProtoMessage()    {}
func (*GameCowcowOver) Descriptor() ([]byte, []int) {
	return fileDescriptor_626b438dd4edf163, []int{3}
}

func (m *GameCowcowOver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameCowcowOver.Unmarshal(m, b)
}
func (m *GameCowcowOver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameCowcowOver.Marshal(b, m, deterministic)
}
func (m *GameCowcowOver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameCowcowOver.Merge(m, src)
}
func (m *GameCowcowOver) XXX_Size() int {
	return xxx_messageInfo_GameCowcowOver.Size(m)
}
func (m *GameCowcowOver) XXX_DiscardUnknown() {
	xxx_messageInfo_GameCowcowOver.DiscardUnknown(m)
}

var xxx_messageInfo_GameCowcowOver proto.InternalMessageInfo

func (m *GameCowcowOver) GetAwardArea() []int32 {
	if m != nil {
		return m.AwardArea
	}
	return nil
}

func (m *GameCowcowOver) GetPlayerCard() []int32 {
	if m != nil {
		return m.PlayerCard
	}
	return nil
}

func (m *GameCowcowOver) GetBankerCard() []int32 {
	if m != nil {
		return m.BankerCard
	}
	return nil
}

func (m *GameCowcowOver) GetAcquire() float32 {
	if m != nil {
		return m.Acquire
	}
	return 0
}

func init() {
	proto.RegisterType((*GameCowcowEnter)(nil), "go.GameCowcowEnter")
	proto.RegisterType((*GameCowcowPlaying)(nil), "go.GameCowcowPlaying")
	proto.RegisterType((*GameCowcowBetResult)(nil), "go.GameCowcowBetResult")
	proto.RegisterType((*GameCowcowOver)(nil), "go.GameCowcowOver")
}

func init() { proto.RegisterFile("cowcow.proto", fileDescriptor_626b438dd4edf163) }

var fileDescriptor_626b438dd4edf163 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0xa4, 0xe9, 0xcf, 0x80, 0x40, 0x18, 0x16, 0x16, 0x42, 0x28, 0xca, 0x2a, 0x2b,
	0x36, 0x9c, 0x20, 0x89, 0x10, 0xb0, 0x2a, 0x72, 0x4f, 0x60, 0x92, 0x51, 0x89, 0x28, 0x71, 0xb1,
	0x5d, 0x22, 0x6e, 0xc0, 0x75, 0xb9, 0x01, 0xf2, 0xb8, 0xad, 0xc3, 0xae, 0xef, 0x7b, 0xd3, 0x67,
	0xcf, 0x73, 0xe0, 0xb4, 0x51, 0x43, 0xa3, 0x86, 0xbb, 0xad, 0x56, 0x56, 0xb1, 0x78, 0xad, 0xf2,
	0xdf, 0x08, 0xce, 0x1f, 0xe5, 0x07, 0xd6, 0x64, 0x3c, 0xf4, 0x16, 0x35, 0xbb, 0x05, 0x28, 0x07,
	0xa9, 0xdb, 0x52, 0xa3, 0x34, 0x3c, 0xca, 0x92, 0x22, 0x15, 0x23, 0xc2, 0x38, 0xcc, 0xb6, 0x1b,
	0xf9, 0x8d, 0xda, 0xf0, 0x38, 0x4b, 0x8a, 0x85, 0x38, 0x48, 0x76, 0x03, 0x8b, 0x5a, 0xed, 0x7a,
	0xdb, 0xaa, 0xa1, 0xe7, 0x49, 0x16, 0x15, 0xa9, 0x08, 0x80, 0x5d, 0x41, 0x5a, 0xbf, 0x75, 0x5b,
	0xc3, 0x27, 0x14, 0xe9, 0x05, 0x63, 0x30, 0x59, 0xb6, 0xad, 0xe1, 0x29, 0x41, 0xfa, 0xcd, 0x32,
	0x38, 0xa9, 0x64, 0xff, 0x8e, 0x7a, 0xd5, 0x28, 0x8d, 0x7c, 0x9a, 0x45, 0x45, 0x2c, 0xc6, 0xc8,
	0x4d, 0xbc, 0xd0, 0xa1, 0x7e, 0x62, 0xe6, 0x27, 0x46, 0xc8, 0xdd, 0xb2, 0x6c, 0x3e, 0x77, 0x9d,
	0x46, 0x3e, 0x27, 0xf7, 0x20, 0xf3, 0x67, 0xb8, 0x08, 0x2b, 0xbb, 0xbf, 0x74, 0xfd, 0xda, 0x8d,
	0x57, 0x68, 0xdd, 0x82, 0x3c, 0xa2, 0x8b, 0x1f, 0x24, 0xbb, 0x86, 0x79, 0x85, 0xd6, 0x9f, 0x13,
	0x53, 0xd2, 0x51, 0xe7, 0x25, 0x5c, 0x86, 0xa8, 0x0a, 0xad, 0x40, 0xb3, 0xdb, 0x58, 0xb7, 0xe9,
	0xca, 0x4a, 0x8b, 0xfb, 0x28, 0x2f, 0x1c, 0x7d, 0xea, 0x7a, 0x6b, 0x28, 0x65, 0x21, 0xbc, 0xc8,
	0x7f, 0x22, 0x38, 0x0b, 0x19, 0xcb, 0x2f, 0xd4, 0xae, 0xc6, 0x63, 0xdd, 0xfb, 0xfe, 0x03, 0x70,
	0xcf, 0xe3, 0xf7, 0xac, 0xa5, 0x6e, 0xe9, 0x05, 0x52, 0x31, 0x22, 0xce, 0xf7, 0x4d, 0x91, 0x9f,
	0x78, 0x3f, 0x90, 0x71, 0x31, 0x93, 0x7f, 0xc5, 0xbc, 0x4e, 0xe9, 0xbb, 0xb8, 0xff, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0x60, 0x18, 0xd8, 0x6d, 0x27, 0x02, 0x00, 0x00,
}
