// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fishLord.proto

package _go

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//【百人类游戏】
//入场 (场景)
type GameFishLordEnter struct {
	AwardAreas           []int32  `protobuf:"varint,1,rep,packed,name=AwardAreas,proto3" json:"AwardAreas,omitempty"`
	Players              []string `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Countdown            int32    `protobuf:"varint,3,opt,name=Countdown,proto3" json:"Countdown,omitempty"`
	Chips                []int32  `protobuf:"varint,4,rep,packed,name=Chips,proto3" json:"Chips,omitempty"`
	Odds                 []int32  `protobuf:"varint,5,rep,packed,name=Odds,proto3" json:"Odds,omitempty"`
	BankerScore          float32  `protobuf:"fixed32,6,opt,name=BankerScore,proto3" json:"BankerScore,omitempty"`
	PlayerScore          float32  `protobuf:"fixed32,7,opt,name=PlayerScore,proto3" json:"PlayerScore,omitempty"`
	Acquire              float32  `protobuf:"fixed32,8,opt,name=Acquire,proto3" json:"Acquire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameFishLordEnter) Reset()         { *m = GameFishLordEnter{} }
func (m *GameFishLordEnter) String() string { return proto.CompactTextString(m) }
func (*GameFishLordEnter) ProtoMessage()    {}
func (*GameFishLordEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd4cc4ee3f27fac1, []int{0}
}

func (m *GameFishLordEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameFishLordEnter.Unmarshal(m, b)
}
func (m *GameFishLordEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameFishLordEnter.Marshal(b, m, deterministic)
}
func (m *GameFishLordEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameFishLordEnter.Merge(m, src)
}
func (m *GameFishLordEnter) XXX_Size() int {
	return xxx_messageInfo_GameFishLordEnter.Size(m)
}
func (m *GameFishLordEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_GameFishLordEnter.DiscardUnknown(m)
}

var xxx_messageInfo_GameFishLordEnter proto.InternalMessageInfo

func (m *GameFishLordEnter) GetAwardAreas() []int32 {
	if m != nil {
		return m.AwardAreas
	}
	return nil
}

func (m *GameFishLordEnter) GetPlayers() []string {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *GameFishLordEnter) GetCountdown() int32 {
	if m != nil {
		return m.Countdown
	}
	return 0
}

func (m *GameFishLordEnter) GetChips() []int32 {
	if m != nil {
		return m.Chips
	}
	return nil
}

func (m *GameFishLordEnter) GetOdds() []int32 {
	if m != nil {
		return m.Odds
	}
	return nil
}

func (m *GameFishLordEnter) GetBankerScore() float32 {
	if m != nil {
		return m.BankerScore
	}
	return 0
}

func (m *GameFishLordEnter) GetPlayerScore() float32 {
	if m != nil {
		return m.PlayerScore
	}
	return 0
}

func (m *GameFishLordEnter) GetAcquire() float32 {
	if m != nil {
		return m.Acquire
	}
	return 0
}

//游戏消息
//游戏中
type GameFishLordPlaying struct {
	BetArea              int32    `protobuf:"varint,1,opt,name=BetArea,proto3" json:"BetArea,omitempty"`
	BetScore             float32  `protobuf:"fixed32,2,opt,name=BetScore,proto3" json:"BetScore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameFishLordPlaying) Reset()         { *m = GameFishLordPlaying{} }
func (m *GameFishLordPlaying) String() string { return proto.CompactTextString(m) }
func (*GameFishLordPlaying) ProtoMessage()    {}
func (*GameFishLordPlaying) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd4cc4ee3f27fac1, []int{1}
}

func (m *GameFishLordPlaying) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameFishLordPlaying.Unmarshal(m, b)
}
func (m *GameFishLordPlaying) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameFishLordPlaying.Marshal(b, m, deterministic)
}
func (m *GameFishLordPlaying) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameFishLordPlaying.Merge(m, src)
}
func (m *GameFishLordPlaying) XXX_Size() int {
	return xxx_messageInfo_GameFishLordPlaying.Size(m)
}
func (m *GameFishLordPlaying) XXX_DiscardUnknown() {
	xxx_messageInfo_GameFishLordPlaying.DiscardUnknown(m)
}

var xxx_messageInfo_GameFishLordPlaying proto.InternalMessageInfo

func (m *GameFishLordPlaying) GetBetArea() int32 {
	if m != nil {
		return m.BetArea
	}
	return 0
}

func (m *GameFishLordPlaying) GetBetScore() float32 {
	if m != nil {
		return m.BetScore
	}
	return 0
}

//下注结果
type GameFishLordBetResult struct {
	State                int32    `protobuf:"varint,1,opt,name=State,proto3" json:"State,omitempty"`
	Hints                string   `protobuf:"bytes,2,opt,name=Hints,proto3" json:"Hints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameFishLordBetResult) Reset()         { *m = GameFishLordBetResult{} }
func (m *GameFishLordBetResult) String() string { return proto.CompactTextString(m) }
func (*GameFishLordBetResult) ProtoMessage()    {}
func (*GameFishLordBetResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd4cc4ee3f27fac1, []int{2}
}

func (m *GameFishLordBetResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameFishLordBetResult.Unmarshal(m, b)
}
func (m *GameFishLordBetResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameFishLordBetResult.Marshal(b, m, deterministic)
}
func (m *GameFishLordBetResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameFishLordBetResult.Merge(m, src)
}
func (m *GameFishLordBetResult) XXX_Size() int {
	return xxx_messageInfo_GameFishLordBetResult.Size(m)
}
func (m *GameFishLordBetResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GameFishLordBetResult.DiscardUnknown(m)
}

var xxx_messageInfo_GameFishLordBetResult proto.InternalMessageInfo

func (m *GameFishLordBetResult) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *GameFishLordBetResult) GetHints() string {
	if m != nil {
		return m.Hints
	}
	return ""
}

//结束
type GameFishLordOver struct {
	AwardArea            []int32  `protobuf:"varint,1,rep,packed,name=AwardArea,proto3" json:"AwardArea,omitempty"`
	PlayerCard           []int32  `protobuf:"varint,2,rep,packed,name=PlayerCard,proto3" json:"PlayerCard,omitempty"`
	BankerCard           []int32  `protobuf:"varint,3,rep,packed,name=BankerCard,proto3" json:"BankerCard,omitempty"`
	Acquire              float32  `protobuf:"fixed32,4,opt,name=Acquire,proto3" json:"Acquire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameFishLordOver) Reset()         { *m = GameFishLordOver{} }
func (m *GameFishLordOver) String() string { return proto.CompactTextString(m) }
func (*GameFishLordOver) ProtoMessage()    {}
func (*GameFishLordOver) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd4cc4ee3f27fac1, []int{3}
}

func (m *GameFishLordOver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameFishLordOver.Unmarshal(m, b)
}
func (m *GameFishLordOver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameFishLordOver.Marshal(b, m, deterministic)
}
func (m *GameFishLordOver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameFishLordOver.Merge(m, src)
}
func (m *GameFishLordOver) XXX_Size() int {
	return xxx_messageInfo_GameFishLordOver.Size(m)
}
func (m *GameFishLordOver) XXX_DiscardUnknown() {
	xxx_messageInfo_GameFishLordOver.DiscardUnknown(m)
}

var xxx_messageInfo_GameFishLordOver proto.InternalMessageInfo

func (m *GameFishLordOver) GetAwardArea() []int32 {
	if m != nil {
		return m.AwardArea
	}
	return nil
}

func (m *GameFishLordOver) GetPlayerCard() []int32 {
	if m != nil {
		return m.PlayerCard
	}
	return nil
}

func (m *GameFishLordOver) GetBankerCard() []int32 {
	if m != nil {
		return m.BankerCard
	}
	return nil
}

func (m *GameFishLordOver) GetAcquire() float32 {
	if m != nil {
		return m.Acquire
	}
	return 0
}

func init() {
	proto.RegisterType((*GameFishLordEnter)(nil), "go.GameFishLordEnter")
	proto.RegisterType((*GameFishLordPlaying)(nil), "go.GameFishLordPlaying")
	proto.RegisterType((*GameFishLordBetResult)(nil), "go.GameFishLordBetResult")
	proto.RegisterType((*GameFishLordOver)(nil), "go.GameFishLordOver")
}

func init() { proto.RegisterFile("fishLord.proto", fileDescriptor_dd4cc4ee3f27fac1) }

var fileDescriptor_dd4cc4ee3f27fac1 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xdb, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xc9, 0x6e, 0xb7, 0x87, 0x11, 0x44, 0xa3, 0x42, 0x10, 0x91, 0x65, 0xaf, 0xf6, 0xca,
	0x1b, 0x9f, 0xa0, 0xbb, 0x78, 0x00, 0x85, 0x4a, 0xfa, 0x04, 0xb1, 0x19, 0xdb, 0xc5, 0x9a, 0xd4,
	0x24, 0xb5, 0xf8, 0x0a, 0xbe, 0xae, 0x2f, 0x20, 0x49, 0x7a, 0x88, 0x77, 0xfb, 0x7f, 0x33, 0xf9,
	0x93, 0xf9, 0x67, 0xe1, 0xf8, 0xad, 0xb3, 0x8b, 0x67, 0x6d, 0xe4, 0xcd, 0xca, 0x68, 0xa7, 0x69,
	0x36, 0xd7, 0xd5, 0x2f, 0x81, 0xd3, 0x07, 0xf1, 0x81, 0xf7, 0xdb, 0xd2, 0x9d, 0x72, 0x68, 0xe8,
	0x35, 0xc0, 0x78, 0x23, 0x8c, 0x1c, 0x1b, 0x14, 0x96, 0x91, 0x32, 0xaf, 0x0b, 0x9e, 0x10, 0xca,
	0x60, 0xb0, 0x5a, 0x8a, 0x6f, 0x34, 0x96, 0x65, 0x65, 0x5e, 0x8f, 0xf8, 0x4e, 0xd2, 0x2b, 0x18,
	0xb5, 0x7a, 0xad, 0x9c, 0xd4, 0x1b, 0xc5, 0xf2, 0x92, 0xd4, 0x05, 0x3f, 0x00, 0x7a, 0x0e, 0x45,
	0xbb, 0xe8, 0x56, 0x96, 0xf5, 0x82, 0x65, 0x14, 0x94, 0x42, 0x6f, 0x22, 0xa5, 0x65, 0x45, 0x80,
	0xe1, 0x9b, 0x96, 0x70, 0xd4, 0x08, 0xf5, 0x8e, 0x66, 0x3a, 0xd3, 0x06, 0x59, 0xbf, 0x24, 0x75,
	0xc6, 0x53, 0xe4, 0x3b, 0x5e, 0xc2, 0xa5, 0xb1, 0x63, 0x10, 0x3b, 0x12, 0xe4, 0x5f, 0x39, 0x9e,
	0x7d, 0xae, 0x3b, 0x83, 0x6c, 0x18, 0xaa, 0x3b, 0x59, 0x3d, 0xc1, 0x59, 0x3a, 0xb4, 0x3f, 0xd4,
	0xa9, 0xb9, 0x3f, 0xd0, 0xa0, 0xf3, 0x23, 0x32, 0x12, 0x9e, 0xbe, 0x93, 0xf4, 0x12, 0x86, 0x0d,
	0xba, 0x78, 0x53, 0x16, 0xbc, 0xf6, 0xba, 0x6a, 0xe1, 0x22, 0x35, 0x6b, 0xd0, 0x71, 0xb4, 0xeb,
	0xa5, 0xf3, 0xd3, 0x4e, 0x9d, 0x70, 0xb8, 0x35, 0x8b, 0xc2, 0xd3, 0xc7, 0x4e, 0x39, 0x1b, 0x7c,
	0x46, 0x3c, 0x8a, 0xea, 0x87, 0xc0, 0x49, 0xea, 0x32, 0xf9, 0x42, 0xe3, 0xc3, 0xdc, 0x87, 0xbe,
	0xdd, 0xc2, 0x01, 0xf8, 0x25, 0xc5, 0x69, 0x5b, 0x61, 0x64, 0xd8, 0x43, 0xc1, 0x13, 0xe2, 0xeb,
	0x31, 0xaf, 0x50, 0xcf, 0x63, 0xfd, 0x40, 0xd2, 0x78, 0x7a, 0xff, 0xe2, 0x79, 0xed, 0x87, 0xff,
	0xe3, 0xf6, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x95, 0x74, 0x6e, 0x6c, 0x31, 0x02, 0x00, 0x00,
}
