// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package _go

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//【百人类游戏】
//入场 (场景)
type GameEnter struct {
	AwardAreas           []int32  `protobuf:"varint,1,rep,packed,name=AwardAreas,proto3" json:"AwardAreas,omitempty"`
	Players              []string `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Countdown            int32    `protobuf:"varint,3,opt,name=Countdown,proto3" json:"Countdown,omitempty"`
	Chips                []int32  `protobuf:"varint,4,rep,packed,name=Chips,proto3" json:"Chips,omitempty"`
	Odds                 []int32  `protobuf:"varint,5,rep,packed,name=Odds,proto3" json:"Odds,omitempty"`
	BankerScore          float32  `protobuf:"fixed32,6,opt,name=BankerScore,proto3" json:"BankerScore,omitempty"`
	PlayerScore          float32  `protobuf:"fixed32,7,opt,name=PlayerScore,proto3" json:"PlayerScore,omitempty"`
	Acquire              float32  `protobuf:"fixed32,8,opt,name=Acquire,proto3" json:"Acquire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameEnter) Reset()         { *m = GameEnter{} }
func (m *GameEnter) String() string { return proto.CompactTextString(m) }
func (*GameEnter) ProtoMessage()    {}
func (*GameEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *GameEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameEnter.Unmarshal(m, b)
}
func (m *GameEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameEnter.Marshal(b, m, deterministic)
}
func (m *GameEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameEnter.Merge(m, src)
}
func (m *GameEnter) XXX_Size() int {
	return xxx_messageInfo_GameEnter.Size(m)
}
func (m *GameEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_GameEnter.DiscardUnknown(m)
}

var xxx_messageInfo_GameEnter proto.InternalMessageInfo

func (m *GameEnter) GetAwardAreas() []int32 {
	if m != nil {
		return m.AwardAreas
	}
	return nil
}

func (m *GameEnter) GetPlayers() []string {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *GameEnter) GetCountdown() int32 {
	if m != nil {
		return m.Countdown
	}
	return 0
}

func (m *GameEnter) GetChips() []int32 {
	if m != nil {
		return m.Chips
	}
	return nil
}

func (m *GameEnter) GetOdds() []int32 {
	if m != nil {
		return m.Odds
	}
	return nil
}

func (m *GameEnter) GetBankerScore() float32 {
	if m != nil {
		return m.BankerScore
	}
	return 0
}

func (m *GameEnter) GetPlayerScore() float32 {
	if m != nil {
		return m.PlayerScore
	}
	return 0
}

func (m *GameEnter) GetAcquire() float32 {
	if m != nil {
		return m.Acquire
	}
	return 0
}

//游戏消息
//游戏中
type GamePlaying struct {
	BetArea              int32    `protobuf:"varint,1,opt,name=BetArea,proto3" json:"BetArea,omitempty"`
	BetScore             float32  `protobuf:"fixed32,2,opt,name=BetScore,proto3" json:"BetScore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamePlaying) Reset()         { *m = GamePlaying{} }
func (m *GamePlaying) String() string { return proto.CompactTextString(m) }
func (*GamePlaying) ProtoMessage()    {}
func (*GamePlaying) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *GamePlaying) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamePlaying.Unmarshal(m, b)
}
func (m *GamePlaying) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamePlaying.Marshal(b, m, deterministic)
}
func (m *GamePlaying) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamePlaying.Merge(m, src)
}
func (m *GamePlaying) XXX_Size() int {
	return xxx_messageInfo_GamePlaying.Size(m)
}
func (m *GamePlaying) XXX_DiscardUnknown() {
	xxx_messageInfo_GamePlaying.DiscardUnknown(m)
}

var xxx_messageInfo_GamePlaying proto.InternalMessageInfo

func (m *GamePlaying) GetBetArea() int32 {
	if m != nil {
		return m.BetArea
	}
	return 0
}

func (m *GamePlaying) GetBetScore() float32 {
	if m != nil {
		return m.BetScore
	}
	return 0
}

//下注结果
type GameBetResult struct {
	State                int32    `protobuf:"varint,1,opt,name=State,proto3" json:"State,omitempty"`
	Hints                string   `protobuf:"bytes,2,opt,name=Hints,proto3" json:"Hints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameBetResult) Reset()         { *m = GameBetResult{} }
func (m *GameBetResult) String() string { return proto.CompactTextString(m) }
func (*GameBetResult) ProtoMessage()    {}
func (*GameBetResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *GameBetResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBetResult.Unmarshal(m, b)
}
func (m *GameBetResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBetResult.Marshal(b, m, deterministic)
}
func (m *GameBetResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBetResult.Merge(m, src)
}
func (m *GameBetResult) XXX_Size() int {
	return xxx_messageInfo_GameBetResult.Size(m)
}
func (m *GameBetResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBetResult.DiscardUnknown(m)
}

var xxx_messageInfo_GameBetResult proto.InternalMessageInfo

func (m *GameBetResult) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *GameBetResult) GetHints() string {
	if m != nil {
		return m.Hints
	}
	return ""
}

//结束
type GameOver struct {
	AwardArea            []int32  `protobuf:"varint,1,rep,packed,name=AwardArea,proto3" json:"AwardArea,omitempty"`
	PlayerCard           []int32  `protobuf:"varint,2,rep,packed,name=PlayerCard,proto3" json:"PlayerCard,omitempty"`
	BankerCard           []int32  `protobuf:"varint,3,rep,packed,name=BankerCard,proto3" json:"BankerCard,omitempty"`
	Acquire              float32  `protobuf:"fixed32,4,opt,name=Acquire,proto3" json:"Acquire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameOver) Reset()         { *m = GameOver{} }
func (m *GameOver) String() string { return proto.CompactTextString(m) }
func (*GameOver) ProtoMessage()    {}
func (*GameOver) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3}
}

func (m *GameOver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameOver.Unmarshal(m, b)
}
func (m *GameOver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameOver.Marshal(b, m, deterministic)
}
func (m *GameOver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameOver.Merge(m, src)
}
func (m *GameOver) XXX_Size() int {
	return xxx_messageInfo_GameOver.Size(m)
}
func (m *GameOver) XXX_DiscardUnknown() {
	xxx_messageInfo_GameOver.DiscardUnknown(m)
}

var xxx_messageInfo_GameOver proto.InternalMessageInfo

func (m *GameOver) GetAwardArea() []int32 {
	if m != nil {
		return m.AwardArea
	}
	return nil
}

func (m *GameOver) GetPlayerCard() []int32 {
	if m != nil {
		return m.PlayerCard
	}
	return nil
}

func (m *GameOver) GetBankerCard() []int32 {
	if m != nil {
		return m.BankerCard
	}
	return nil
}

func (m *GameOver) GetAcquire() float32 {
	if m != nil {
		return m.Acquire
	}
	return 0
}

func init() {
	proto.RegisterType((*GameEnter)(nil), "go.GameEnter")
	proto.RegisterType((*GamePlaying)(nil), "go.GamePlaying")
	proto.RegisterType((*GameBetResult)(nil), "go.GameBetResult")
	proto.RegisterType((*GameOver)(nil), "go.GameOver")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0xa4, 0x69, 0x9b, 0xab, 0x58, 0x2c, 0x06, 0x0b, 0x21, 0x14, 0x65, 0xca, 0xc4,
	0xc2, 0xc8, 0xd4, 0x44, 0x08, 0xb6, 0x22, 0xf7, 0x09, 0x4c, 0x73, 0x2a, 0x11, 0xad, 0x5d, 0x6c,
	0x97, 0x8a, 0x95, 0xd7, 0xe5, 0x25, 0xd0, 0xd9, 0x4d, 0x13, 0x36, 0xff, 0xdf, 0xfd, 0x3e, 0xfb,
	0xfe, 0x03, 0xd8, 0xaa, 0x3d, 0xde, 0x1f, 0xac, 0xf1, 0x86, 0x27, 0x5b, 0x53, 0xfe, 0x32, 0xc8,
	0x9f, 0xd5, 0x1e, 0x9f, 0xb4, 0x47, 0xcb, 0xef, 0x00, 0x96, 0x27, 0x65, 0xdb, 0xa5, 0x45, 0xe5,
	0x04, 0x2b, 0xd2, 0x2a, 0x93, 0x23, 0xc2, 0x05, 0xcc, 0x0e, 0x3b, 0xf5, 0x8d, 0xd6, 0x89, 0xa4,
	0x48, 0xab, 0x5c, 0xf6, 0x92, 0xdf, 0x42, 0xde, 0x98, 0xa3, 0xf6, 0xad, 0x39, 0x69, 0x91, 0x16,
	0xac, 0xca, 0xe4, 0x00, 0xf8, 0x35, 0x64, 0xcd, 0x7b, 0x77, 0x70, 0x62, 0x12, 0x5a, 0x46, 0xc1,
	0x39, 0x4c, 0x56, 0x6d, 0xeb, 0x44, 0x16, 0x60, 0x38, 0xf3, 0x02, 0x16, 0xb5, 0xd2, 0x1f, 0x68,
	0xd7, 0x1b, 0x63, 0x51, 0x4c, 0x0b, 0x56, 0x25, 0x72, 0x8c, 0xc8, 0xf1, 0x1a, 0x1e, 0x8d, 0x8e,
	0x59, 0x74, 0x8c, 0x10, 0xfd, 0x72, 0xb9, 0xf9, 0x3c, 0x76, 0x16, 0xc5, 0x3c, 0x54, 0x7b, 0x59,
	0x36, 0xb0, 0xa0, 0x61, 0xc9, 0xdc, 0xe9, 0x2d, 0x19, 0x6b, 0xf4, 0x34, 0x9a, 0x60, 0xe1, 0xcb,
	0xbd, 0xe4, 0x37, 0x30, 0xaf, 0xd1, 0xc7, 0x17, 0x92, 0xd0, 0xe3, 0xa2, 0xcb, 0x47, 0xb8, 0xa2,
	0x26, 0x35, 0x7a, 0x89, 0xee, 0xb8, 0xf3, 0x34, 0xdd, 0xda, 0x2b, 0x8f, 0xe7, 0x26, 0x51, 0x10,
	0x7d, 0xe9, 0xb4, 0x77, 0xe1, 0x7e, 0x2e, 0xa3, 0x28, 0x7f, 0x18, 0xcc, 0xe9, 0xf6, 0xea, 0x0b,
	0x2d, 0x85, 0x76, 0x09, 0xf7, 0x9c, 0xf6, 0x00, 0x68, 0x19, 0x71, 0xaa, 0x46, 0xd9, 0x36, 0xe4,
	0x9d, 0xc9, 0x11, 0xa1, 0x7a, 0xcc, 0x25, 0xd4, 0xd3, 0x58, 0x1f, 0xc8, 0x38, 0x86, 0xc9, 0xbf,
	0x18, 0xde, 0xa6, 0x61, 0xff, 0x0f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x86, 0xf9, 0x65, 0xdc,
	0x0d, 0x02, 0x00, 0x00,
}
