//---------------------------------
//该文件自动生成，请勿手动更改
//---------------------------------
package gate

import (
    "miniRobot/game"
    "miniRobot/login"
    "miniRobot/msg"
    protoMsg "miniRobot/msg/go"
)

//路由模块分发消息【模块间使用 ChanRPC 通讯，消息路由也不例外】
//注:需要解析的结构体才进行路由分派，即用客户端主动发起的)
func init() {
    //login文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.UserInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TableInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MasterInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TaskItem{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ClassItem{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameItem{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TableItem{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TaskList{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ClassList{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameList{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TableList{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RegisterReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RegisterResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LoginReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LoginResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.AllopatricResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ReconnectReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ReconnectResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.UpdateMoneyReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.UpdateMoneyResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RechargeReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RechargeResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChooseClassReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChooseClassResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChooseGameReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChooseGameResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SettingTableReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SettingTableResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ResultResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ResultPopResp{}, login.ChanRPC)

    //comand文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.PacketData{}, game.ChanRPC)

    //gamecomm文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.PlayerInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GoodsInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EmailInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.CardInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TimeInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.AreaInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.InningInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.PlayerListInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.PlayerRecord{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameRecord{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameRecordList{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ExitGameReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ExitGameResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChangeTableReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChangeTableResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TrusteeReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TrusteeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RollDiceReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RollDiceResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.UpdateGoldReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.UpdateGoldResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetInningsInfoReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetInningsInfoResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameOverReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EmailReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EmailResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ClaimReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ClaimResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SuggestReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SuggestResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.NotifyBeOut{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.NotifyGoldChange{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.NotifyNoticeReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.NotifyNoticeResp{}, game.ChanRPC)

    //baccarat文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratSuperHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratSuperHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratCheckoutResp{}, game.ChanRPC)

    //cowcow文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.GameCowcowEnter{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameCowcowHost{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameCowcowSuperHost{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameCowcowReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameCowcowBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameCowcowOver{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameCowcowCheckout{}, game.ChanRPC)

    //landLords文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsStateCallResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsStateDoubleResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsBottomCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsCallReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsCallResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsDoubleReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsDoubleResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsMingReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsMingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsTrusteeReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsTrusteeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsOutCardReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsOutCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsCheckoutResp{}, game.ChanRPC)

    //mahjong文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongKeZi{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongHint{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameMJResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateDirectResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateDecideResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateRollDiceResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateWaitOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongRollReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongRollResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongOutCardReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongOutCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongOperateReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongHintResp{}, game.ChanRPC)

    //fishLord文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.GameFishLordEnter{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameFishLordPlaying{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameFishLordBetResult{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameFishLordOver{}, game.ChanRPC)

    //brcowcow文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowHostListReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowHostListResp{}, game.ChanRPC)

    //zhajinhua文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameZJHResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaStateCompareResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaTurnResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaFollowReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaFollowResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaRaiseReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaRaiseResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaLookReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaLookResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaCompareReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaCompareResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaGiveupReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaGiveupResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaCheckoutResp{}, game.ChanRPC)

    //brtoubao文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoCheckoutResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoSuperHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoSuperHostResp{}, game.ChanRPC)

    //tigerXdragon文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonCheckoutResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonSuperHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonSuperHostResp{}, game.ChanRPC)

    //tuitongzi文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziCheckoutResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziSuperHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziSuperHostResp{}, game.ChanRPC)

    //tbcowcow文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameTBCCResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowStateDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowOverResp{}, game.ChanRPC)

    //qzcowcow文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameQZCCResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowStateCallResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowStateDecideResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowStateDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowCallReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowCallResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowOverResp{}, game.ChanRPC)

    //sangong文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.SangongPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameSGResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongStateCallResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongStateDecideResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongStateDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongCallReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongCallResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongOutCardReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongOutCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongOverResp{}, game.ChanRPC)

    //mahjongER文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERKeZi{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERHint{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameMJERResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStateDirectResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStateDecideResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStateRollDiceResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStateWaitOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERRollReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERRollResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongEROutCardReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongEROutCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongEROperateReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongEROperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERHintResp{}, game.ChanRPC)
}

