//---------------------------------
//该文件自动生成，请勿手动更改
//---------------------------------
package gate

import (
    "miniRobot/game"
    "miniRobot/login"
    "miniRobot/msg"
    protoMsg "miniRobot/msg/go"
)

//路由模块分发消息【模块间使用 ChanRPC 通讯，消息路由也不例外】
//注:需要解析的结构体才进行路由分派，即用客户端主动发起的)
func init() {
    //login文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.UserInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.WeaponInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GoodsInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.KnapsackInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EmailInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TableInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MasterInfo{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TaskItem{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ClassItem{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameItem{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TableItem{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TaskList{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ClassList{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameList{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TableList{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RegisterReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RegisterResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LoginReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LoginResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.AllopatricResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ReconnectReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ReconnectResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.UpdateMoneyReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.UpdateMoneyResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RechargeReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RechargeResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetGoodsReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetGoodsResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetAllGoodsReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetAllGoodsResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BuyGoodsReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BuyGoodsResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.CheckKnapsackReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.CheckKnapsackResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EmailReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EmailResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ClaimReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ClaimResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SuggestReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SuggestResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChooseClassReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChooseClassResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChooseGameReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChooseGameResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SettingTableReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SettingTableResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ResultResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ResultPopResp{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.PingReq{}, login.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.PongResp{}, login.ChanRPC)

    //comand文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.PacketData{}, game.ChanRPC)

    //gamecomm文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.PlayerInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.CardInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TimeInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.AreaInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.InningInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.PlayerListInfo{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.PlayerRecord{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameRecord{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameRecordList{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ExitGameReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ExitGameResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.DisbandedGameReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.DisbandedGameResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChangeTableReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ChangeTableResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetBackPasswordReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetBackPasswordResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TrusteeReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TrusteeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RollDiceReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.RollDiceResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.UpdateGoldReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.UpdateGoldResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetInningsInfoReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetInningsInfoResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetRecordReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GetRecordResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameOverReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.NotifyBeOut{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.NotifyGoldChange{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.NotifyNoticeReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.NotifyNoticeResp{}, game.ChanRPC)

    //baccarat文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratSuperHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratSuperHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BaccaratCheckoutResp{}, game.ChanRPC)

    //fishLord文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.GameFishLordEnter{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameFishLordPlaying{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameFishLordBetResult{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.GameFishLordOver{}, game.ChanRPC)

    //brcowcow文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowHostListReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrcowcowHostListResp{}, game.ChanRPC)

    //brtoubao文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoCheckoutResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoSuperHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrtoubaoSuperHostResp{}, game.ChanRPC)

    //tigerXdragon文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonCheckoutResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonSuperHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TigerXdragonSuperHostResp{}, game.ChanRPC)

    //brtuitongzi文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziCheckoutResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziSuperHostReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.BrTuitongziSuperHostResp{}, game.ChanRPC)

    //tuitongzi文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameTTZResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziStateDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziOutCardReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziOutCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TuitongziOverResp{}, game.ChanRPC)

    //qzcowcow文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameQZCCResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowStateCallResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowStateDecideResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowStateDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowCallReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowCallResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.QzcowcowOverResp{}, game.ChanRPC)

    //tbcowcow文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameTBCCResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowStateDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowShowCardReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowShowCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.TbcowcowOverResp{}, game.ChanRPC)

    //sangong文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.SangongPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameSGResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongStateCallResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongStateDecideResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongStateDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongCallReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongCallResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongBetReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongBetResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongOutCardReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongOutCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.SangongOverResp{}, game.ChanRPC)

    //zhajinhua文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameZJHResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaStateCompareResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaTurnResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaHostResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaFollowReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaFollowResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaRaiseReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaRaiseResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaLookReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaLookResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaCompareReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaCompareResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaGiveupReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaGiveupResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaCheckoutResp{}, game.ChanRPC)

    //zhajinhuajisu文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaJiSuPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameZJHJiSuResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaJiSuSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaJiSuStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaJiSuStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaJiSuDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaJiSuStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaJiSuStateCompareResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaJiSuStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaJiSuReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaJiSuReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaJiSuFollowResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaJiSuRaiseReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaJiSuRaiseResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaJiSuCompareResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.ZhajinhuaJiSuCheckoutResp{}, game.ChanRPC)

    //landLords文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsStateCallResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsStateDoubleResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsBottomCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsCallReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsCallResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsDoubleReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsDoubleResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsMingReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsMingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsTrusteeReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsTrusteeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsOutCardReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsOutCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.LandLordsCheckoutResp{}, game.ChanRPC)

    //mahjong文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongKeZi{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongHint{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameMJResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateDirectResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateDecideResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateRollDiceResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateWaitOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongRollReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongRollResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongOutCardReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongOutCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongOperateReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongHintResp{}, game.ChanRPC)

    //mahjongER文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERKeZi{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERHint{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameMJERResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStateDirectResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStateDecideResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStateRollDiceResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStateWaitOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERRollReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERRollResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongEROutCardReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongEROutCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongEROperateReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongEROperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongERHintResp{}, game.ChanRPC)

    //mahjongCS文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSKeZi{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSHint{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameMJCSResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSStateDirectResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSStateDecideResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSStateRollDiceResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSStateWaitOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSRollReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSRollResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSOutCardReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSOutCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSOperateReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongCSHintResp{}, game.ChanRPC)

    //mahjongGD文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDKeZi{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDHint{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameMJGDResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDStateDirectResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDStateDecideResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDStateRollDiceResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDStateWaitOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDRollReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDRollResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDOutCardReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDOutCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDOperateReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongGDHintResp{}, game.ChanRPC)

    //mahjongSC文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCKeZi{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCHint{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameMJSCResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCStateDirectResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCStateDecideResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCStateRollDiceResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCStateWaitOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCRollReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCRollResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCOutCardReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCOutCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCOperateReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongSCHintResp{}, game.ChanRPC)

    //mahjongXLCH文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHKeZi{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHHint{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameMJXLCHResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHStateDecideResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHStateRollDiceResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHStateExchangeThreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHStateDingQueResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHStateWaitOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHRollReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHRollResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHExchangeReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHExchangeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHQueMenReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHQueMenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHOutCardReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHOutCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHOperateReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXLCHHintResp{}, game.ChanRPC)

    //mahjongXZDD文件生成的代码
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDKeZi{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDHint{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDPlayer{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.EnterGameMJXZDDResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDSceneResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDStateFreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDStateDecideResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDStateRollDiceResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDStateStartResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDStateExchangeThreeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDStateDingQueResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDStatePlayingResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDStateWaitOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDStateOpenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDStateOverResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDDealResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDReadyReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDReadyResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDRollReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDRollResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDExchangeReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDExchangeResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDQueMenReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDQueMenResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDOutCardReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDOutCardResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDOperateReq{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDOperateResp{}, game.ChanRPC)
    msg.ProcessorProto.SetRouter(&protoMsg.MahjongXZDDHintResp{}, game.ChanRPC)
}


